Add template lag to troubleshooting
wpilibsuite/frc-docs pull request #1018
Opened 2020-12-19 06:38 UTC by Piphi5

The current FRC-Char template prints the number of data samples collected and the time spent collecting after exiting autonomous. This just adds some troubleshooting options that can be done utilizing this feature.

2021-01-08 22:00 UTC, Daltz333 requested changes

2021-01-08 22:00 UTC, Daltz333 commented on source/docs/software/wpilib-tools/robot-characterization/viewing-diagnostics.rst
>  ------------------------------------------
Title overline here

2021-01-23 04:28 UTC, Daltz333 commented
Needs a rebase

2021-01-24 01:47 UTC, Piphi5 commented
> Needs a rebase

Done.

2021-01-24 03:32 UTC, Daltz333 requested changes

2021-01-24 03:32 UTC, Daltz333 commented on source/docs/software/wpilib-tools/robot-characterization/viewing-diagnostics.rst
> +~~~~~~~~~~~~~~~~~~~~
```suggestion
^^^^^^^^^^^^^^^^^^^^
```

2021-01-27 03:46 UTC, Daltz333 approved these changes

2021-01-27 03:46 UTC, merged

2021-01-27 17:40 UTC, calcmogul commented on source/docs/software/wpilib-tools/robot-characterization/viewing-diagnostics.rst
> +To see if this is the case, enable print statements on the Driver Station whenever running the data logger. When Autonomous mode is exited, the console will output ``Collected : n in t seconds`` wher
What's `200t`?