Add docs for newly added widgets
wpilibsuite/frc-docs pull request #1026
Opened 2020-12-22 03:54 UTC by prateekma

Docs for https://github.com/wpilibsuite/allwpilib/pull/2947

2020-12-23 05:12 UTC, prateekma commented
Should be ready to go / review now.

2020-12-23 18:17 UTC, TheTripleV requested changes

2020-12-23 18:17 UTC, TheTripleV commented on source/docs/software/wpilib-tools/glass/command-based-widgets.rst
> +.. image:: images/command-selector.png
```suggestion
.. image:: images/command-selector.png
   :alt: Command Selector widget showing that "MyCommand" is running with the option to cancel
```

2020-12-23 18:17 UTC, TheTripleV commented on source/docs/software/wpilib-tools/glass/command-based-widgets.rst
> +.. image:: images/subsystem.png
```suggestion
.. image:: images/subsystem.png
   :alt: Subsystem widget showing the state of "DriveSubsystem". Default Command: "DefaultDrive". Current Command: "DriveDistance"
```

2020-12-23 18:17 UTC, TheTripleV commented on source/docs/software/wpilib-tools/glass/command-based-widgets.rst
> +.. image:: images/scheduler.png
```suggestion
.. image:: images/scheduler.png
   :alt: Scheduler widget. Scheduled commands are "DriveDistance" and "MyCommand". Both have the option to cancel.
```

2020-12-23 18:17 UTC, TheTripleV commented on source/docs/software/wpilib-tools/glass/widgets.rst
> + .. image:: images/gyro.png
```suggestion
 .. image:: images/gyro.png
    :alt: Gyro widget with both text and dial visualizations of the current gyro angle. Current Gyro Angle in degrees is -60.9704.
```

2020-12-23 18:17 UTC, TheTripleV commented on source/docs/software/wpilib-tools/glass/widgets.rst
> +.. image:: images/pid.png
```suggestion
.. image:: images/pid.png
   :alt: PID widget for the Elevator PID Controller. P = 3.0, I = 0.001, D = 0.050, Setpoint = 0.0.
```

2020-12-24 17:15 UTC, PeterJohnson approved these changes

2020-12-24 19:18 UTC, merged