Update New project creation
wpilibsuite/frc-docs pull request #1047
Opened 2021-01-01 19:48 UTC by sciencewhiz

Matches wpilibsuite/vscode-wpilib#425

2021-01-02 05:17 UTC, AustinShalit requested changes

2021-01-02 05:17 UTC, AustinShalit commented on source/docs/zero-to-robot/step-4/creating-benchtop-test-program-cpp-java.rst
>  8. **Desktop Support**: Enables unit test and simulation. While WPILib supports this, third party software libraries may not. If libraries do not support desktop, then your code may not compile or ma
```suggestion
8. **Enable Desktop Support**: Enables unit test and simulation. While WPILib supports this, third party software libraries may not. If libraries do not support desktop, then your code may not compile or may crash. It should be left unchecked unless unit testing or simulation is needed and all libraries support it. For this example, do not check this box.
```

2021-01-02 05:17 UTC, AustinShalit commented on source/docs/software/vscode-overview/creating-robot-program.rst
>  8. **Desktop Support**: Enables unit test and simulation. While WPILib supports this, third party software libraries may not. If libraries do not support desktop, then your code may not compile or ma
```suggestion
8. **Enable Desktop Support**: Enables unit test and simulation. While WPILib supports this, third party software libraries may not. If libraries do not support desktop, then your code may not compile or may crash. It should be left unchecked unless unit testing or simulation is needed and all libraries support it.
```

2021-01-02 05:17 UTC, AustinShalit commented on source/docs/software/vscode-overview/creating-robot-program.rst
> +6. **Create New Folder**: If this is checked, a new folder will be created to hold the project within the previously-specified folder.  If it is *not* checked, the project will be located directly in
```suggestion
6. **Create a New Folder**: If this is checked, a new folder will be created to hold the project within the previously-specified folder.  If it is *not* checked, the project will be located directly in the previously-specified folder.  An error will be thrown if the folder is not empty and this is not checked.
```

2021-01-02 15:57 UTC, Daltz333 approved these changes

2021-01-03 02:42 UTC, AustinShalit approved these changes

2021-01-03 02:42 UTC, merged