Add danger notice at the top of ML docs
wpilibsuite/frc-docs pull request #1096
Opened 2021-01-16 06:23 UTC by Daltz333

Current ML solution does not work. The INFINITERECHARGEATHOME manual [links](https://firstfrc.blob.core.windows.net/frc2021/Manual/AtHomeChallengesSupplements/2021INFINITERECHARGEatHome-Guides.pdf) to this. This PR adds a danger notice to the top of each ML page advising users to invest in a tensorflow solution until [Axon](https://github.com/wpilibsuite/axon) is stable and documented.

2021-01-16 06:37 UTC, GrantPerkins commented
I think this link may be a bit more appropriate/helpful: [Coral docs](https://coral.ai/docs/edgetpu/retrain-detection/)

2021-01-16 06:38 UTC, GrantPerkins commented
Otherwise, I think this looks fine.

2021-01-16 06:38 UTC, GrantPerkins requested changes
Use link in above comment, please.

2021-01-18 22:14 UTC, GrantPerkins approved these changes

2021-01-19 02:55 UTC, AustinShalit approved these changes

2021-01-19 02:55 UTC, merged