Document the drive classes and their commonly used features
wpilibsuite/frc-docs pull request #1132
Opened 2021-01-22 02:45 UTC by jasondaming

Closes #1109

2021-01-22 07:22 UTC, Daltz333 commented
I don't believe this fully solves the issue. @calcmogul

2021-01-24 17:46 UTC, Daltz333 commented
I believe Tyler wanted examples of
```
.arcadeDrive()
.tankDrive()
.curvatureDrive()
```

```
driveCartesian()
drivePolar()
```

2021-01-24 20:04 UTC, jasondaming commented
You mean like the example code in the article:
```
public void teleopPeriodic() {
    // Tank drive with a given left and right rates
    myDrive.tankDrive(leftStick.getY(), rightStick.getY());

    // Arcade drive with a given forward and turn rate
    myDrive.arcadeDrive(driveStick.getY(),driveStick.getX());

    // Curvature drive with a given forward and turn rate, as well as a quick-turn button
    myDrive.curvatureDrive(driveStick.getY(), driveStick.getX(), driveStick.getButton(1));
}```

2021-01-24 20:06 UTC, jasondaming commented
And then this one:
```public void teleopPeriodic() {
    m_robotDrive.driveCartesian(m_stick.getX(), m_stick.getY(), m_stick.getZ());
    m_robotDrive.drivePolar(m_stick.getX(), m_stick.getY(), m_stick.getZ());
}```

2021-01-25 03:51 UTC, calcmogul requested changes

2021-01-25 03:51 UTC, calcmogul commented on source/docs/software/actuators/wpi-drive-classes.rst
> +By default, the Differential Drive class applies an input deadband of .02. This means that input values with a magnitude below .02 (after any squaring as described above) will be set to 0. In most ca
```suggestion
By default, the Differential Drive class applies an input deadband of 0.02. This means that input values with a magnitude below 0.02 (after any squaring as described above) will be set to 0. In most cases these small inputs result from imperfect joystick centering and are not sufficient to cause drivetrain movement, the deadband helps reduce unnecessary motor heating that may result from applying these small values to the drivetrain. To change the deadband, use the `setDeadband()` method.
```

2021-02-05 01:25 UTC, jasondaming commented
@calcmogul / @Daltz333 is there anything else that needs to be done on this PR?

2021-02-05 01:26 UTC, Daltz333 commented
I was waiting on Tyler's review to make sure it adequately addressed his comments

2021-02-05 01:28 UTC, calcmogul approved these changes

2021-02-05 03:09 UTC, Daltz333 approved these changes

2021-02-05 03:09 UTC, merged