Add gradle cache known issue
wpilibsuite/frc-docs pull request #1193
Opened 2021-02-06 14:54 UTC by Daltz333

2021-02-06 15:29 UTC, prateekma reviewed
I'm not sure if this actually fixes the issue: https://www.chiefdelphi.com/t/wpilib-build-error/390971/20?u=prateek_m

2021-02-06 15:46 UTC, Daltz333 commented
It's only some errors, also, I commited on that post.

2021-02-07 03:58 UTC, Daltz333 commented
I've updated the known-issue document with just the gradlerio specific problem.

2021-02-09 04:57 UTC, Daltz333 commented
Thoughts Austin?

2021-03-08 03:40 UTC, AustinShalit requested changes

2021-03-08 03:40 UTC, AustinShalit commented on source/docs/yearly-overview/known-issues.rst
> +**Issue:** Rarely, a users gradle cache will get broken and they will get shown errors similar to the following:
```suggestion
**Issue:** Rarely, a user's Gradle cache will get broken and they will get shown errors similar to the following:
```

2021-03-08 03:40 UTC, AustinShalit commented on source/docs/yearly-overview/known-issues.rst
> +Delete your gradle cache located under ``~$USER_HOME/.gradle``. Windows machines may need to enable the ability to `view hidden files <https://support.microsoft.com/en-us/windows/view-hidden-files-an
```suggestion
Delete your Gradle cache located under ``~$USER_HOME/.gradle``. Windows machines may need to enable the ability to `view hidden files <https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-10-97fbc472-c603-9d90-91d0-1166d1d9f4b5>`__. This issue has only shown up on Windows so far. Please `report <https://github.com/wpilibsuite/frc-docs/issues/new>`__ this issue if you get it on an alternative OS.
```

2021-03-08 05:21 UTC, AustinShalit approved these changes

2021-03-08 05:23 UTC, merged