Image Filenames and Accessibility
wpilibsuite/frc-docs pull request #1209
Opened 2021-02-09 17:49 UTC by jasondaming

Closes #225

2021-02-09 17:52 UTC, jasondaming commented
@prateekma & @Daltz333 hopefully this is easier to review

2021-02-10 15:30 UTC, Daltz333 submitted a review, later dismissed
This looks fantastic, thank you a ton. This is great work. I'd like at least two others to give it a review before merging since it's so widely touching.

2021-02-12 10:06 UTC, Modelmat requested changes
I did the hardware section and then gave up... There's *a lot* there.

Most of the alt-texts seem to have similar issues in that it's not a description of the actual content of the image, but a description of what the image is, which means the alt text is not-so-useful.

Also, do we have a way to create a check for the existence of alt-text on images?

2021-02-12 14:43 UTC, jasondaming commented
In general I got feedback that using "shows/showing" was superfluous and I agree.  Some things that are a picture of an object are hard to describe unless I actually try to describe the physical properites of the object, but is that helpful?

As you said it was a ton of work.  Some things may have just been due to my brain melting towards the end!

2021-02-12 14:45 UTC, jasondaming commented on source/docs/hardware/hardware-basics/status-lights-ref.rst
> +  :alt: Highlights the VRM 12V and 5V lights.
What benefit does "showing" add here?  I originally had this terminology but cut it due to comments.  I could add status

2021-02-12 14:46 UTC, jasondaming commented on source/docs/hardware/hardware-basics/wiring-pneumatics.rst
> +   :alt: The "VSOL" jumper in the center with the 12V and 24V showing the left and right positions of the jumper respectively.
Why does this image need a width?  @Daltz333 is very anti width.  I like it because (for some reason) it makes the image clickable.

2021-02-12 20:51 UTC, jasondaming commented on source/docs/hardware/sensors/accelerometers-hardware.rst
> +  :alt: The triple axis accelerometer hooked up to three different Analog In channels.
I think this doesn't really clarify anything

2021-02-12 20:51 UTC, jasondaming commented on source/docs/hardware/hardware-basics/wiring-pneumatics.rst
> +   :alt: The "VSOL" jumper in the center with the 12V and 24V showing the left and right positions of the jumper respectively.
added of the PCM

2021-02-12 20:52 UTC, jasondaming commented on source/docs/hardware/hardware-basics/status-lights-ref.rst
> +  :alt: Highlights the VRM 12V and 5V lights.
Modified to include the extra details

2021-02-12 20:53 UTC, jasondaming commented on source/docs/hardware/sensors/accelerometers-hardware.rst
> +  :alt: The details of this accelerometer are on the roboRIO to the right of the NI logo.
added printed.

2021-02-12 20:55 UTC, jasondaming commented on source/docs/hardware/sensors/analog-inputs-hardware.rst
> +   :alt: Highlights the Analog In section of the roboRIO.
used

2021-02-12 20:57 UTC, jasondaming commented on source/docs/hardware/sensors/analog-inputs-hardware.rst
> +   :alt: Hooking a triple axis accelerometer to three different analog input channels.
done

2021-02-12 20:58 UTC, jasondaming commented on source/docs/hardware/sensors/analog-potentiometers-hardware.rst
> +   :alt: Wiring a potentiometer.
done

2021-02-12 21:02 UTC, jasondaming commented on source/docs/hardware/sensors/digital-inputs-hardware.rst
> +   :alt: Connecting a NO limit switch to a DIO channel of the roboRIO.
changed to normally open.  It is discussed in other articles but not this one.

2021-02-14 00:24 UTC, Modelmat commented on source/docs/hardware/hardware-basics/status-lights-ref.rst
> +  :alt: Highlights the VRM 12V and 5V lights.
I think that "showing" is generally superfluous - however, I'm not sure what WPILib is going for with alt-text.

The way I understood alt-text for accessibility (i.e. you are blind and need a screen-reader) is that the alt-text should describe the contents of the image (i.e. it describes what the actual picture is of and the important details within in).

Hence, "Highlights the position of the 12V and 5V status lights." isn't really useful as it requires the knowledge that you have a VRM in the picture.

2021-02-23 14:22 UTC, Daltz333 approved these changes

2021-02-23 14:23 UTC, Daltz333 requested changes
Can you force-push so a new RTD build is triggered?

2021-03-05 02:10 UTC, sciencewhiz approved these changes

2021-03-05 02:24 UTC, Daltz333 approved these changes
I'm approving, and will merge in the next day or so assuming no other concerns are brought up.

2021-03-05 18:44 UTC, merged