Fix formatting issue. Add Raspberry PI jni lib.
wpilibsuite/frc-docs pull request #1212
Opened 2021-02-10 05:13 UTC by agasser

Fix improperly formatted text in example.
Add Raspberry PI JNI library. The comment says it is adding all supported platforms. Additionally Raspberry Pi is a good use case for a standalone NetworkTables client.

2021-02-10 05:23 UTC, sciencewhiz requested changes

2021-02-10 05:23 UTC, sciencewhiz commented on source/docs/software/networktables/client-side-program.rst
> +
Fix trailing white space
```suggestion

```

2021-02-10 05:56 UTC, agasser commented on source/docs/software/networktables/client-side-program.rst
> +
Fixed

2021-02-10 15:15 UTC, Daltz333 commented
Should the comment get removed?

2021-02-10 15:42 UTC, agasser commented
> Should the comment get removed?

That's a good question. It is helpful to have all of the environments in the example, otherwise another section should be added to explain. In my use case I was using a Raspberry Pi and I had to solve it myself when I got an error attempting to run it.

2021-02-11 15:19 UTC, Daltz333 approved these changes

2021-02-11 15:19 UTC, merged