add better example for slew rate limiter
wpilibsuite/frc-docs pull request #1272
Opened 2021-03-20 15:54 UTC by Oblarg

2021-03-20 15:56 UTC, Daltz333 commented on source/docs/software/advanced-controls/filters/slew-rate-limiter.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
Using a SlewRateLimiter with DifferentialDrive
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2021-03-20 16:05 UTC, Daltz333 commented
@prateekma could you verify C++?

2021-03-20 19:14 UTC, prateekma requested changes
I would also prefer if we showed users how to construct the filter here. The above example uses one templated on units::volts and that clearly won't work here.

2021-03-20 19:14 UTC, prateekma commented on source/docs/software/advanced-controls/filters/slew-rate-limiter.rst
> +    driveTrain.arcadeDrive(filter.calculate(forward), turn);
`driveTrain` -> `drivetrain`

2021-03-20 19:14 UTC, prateekma commented on source/docs/software/advanced-controls/filters/slew-rate-limiter.rst
> +    driveTrain.ArcadeDrive(filter.Calculate(forward), turn);
`driveTrain` -> `drivetrain`

2021-04-16 00:59 UTC, Daltz333 commented
@Oblarg update on prateeks review

2021-04-16 01:50 UTC, Oblarg commented
I don't see any clear way to show how to construct it for C++ without breaking the flow of the article.  I added an explanatory note, instead.

2021-04-16 01:56 UTC, Daltz333 commented
I was talking about renaming driveTrain to drivetrain

2021-04-16 03:33 UTC, Oblarg commented
Oh, I edited those in the wrong direction, it seems.

2021-04-18 23:17 UTC, Daltz333 approved these changes

2021-04-18 23:17 UTC, merged