Replace MikTex with TexLive
wpilibsuite/frc-docs pull request #1330
Opened 2021-04-23 17:35 UTC by Daltz333

Still testing and verifying.

Closes #1323

2021-04-24 14:15 UTC, Daltz333 commented
Good for review and merge

2021-04-25 02:20 UTC, TheTripleV requested changes

2021-04-25 02:20 UTC, TheTripleV commented on source/docs/contributing/frc-docs/build-instructions.rst
> +.. note:: MikTeX and ``rsvg-convert`` is not required for building HTML, it is only required for Windows PDF builds.
```suggestion
.. note:: MikTeX and ``rsvg-convert`` are not required for building HTML, they are only required for Windows PDF builds.
```

2021-04-25 23:05 UTC, Daltz333 commented
Don't merge yet. Need to update MikTex packages. tools got renamed to latex-tools

2021-04-28 02:57 UTC, jasondaming approved these changes

2021-04-28 02:57 UTC, merged