Replace game specific information
wpilibsuite/frc-docs pull request #1370
Opened 2021-06-04 19:12 UTC by Daltz333

2021-06-04 23:23 UTC, AustinShalit submitted a review, later dismissed

2021-06-05 01:13 UTC, AustinShalit commented on source/docs/networking/networking-introduction/measuring-bandwidth-usage.rst
> +On the FRC\ |reg| Field (and at home when the radio is configured using the FRC Bridge Configuration Utility) each team is allocated limited (see `R60B <https://firstfrc.blob.core.windows.net/frc2021
Reading this again:
```
and at home when the radio is configured using the FRC Bridge Configuration Utility
```

This is only accurate when the bandwidth setting is set.

2021-06-05 18:16 UTC, Starlight220 requested changes

2021-06-05 18:16 UTC, Starlight220 commented on source/docs/networking/networking-introduction/measuring-bandwidth-usage.rst
> +On the FRC\ |reg| Field (and at home when the radio is configured using the FRC Bridge Configuration Utility with the bandwidth checkbox checked) each team is allocated limited (see `R60B <https://fi
Perhaps merge the two "see x for more details" parentheses? It greatly disrupts the sentence's flow.

2021-06-09 13:35 UTC, Kevin-OConnor approved these changes

2021-06-09 15:15 UTC, merged