Add information on supported Gradle tasks
wpilibsuite/frc-docs pull request #1374
Opened 2021-06-06 16:06 UTC by Daltz333

Close #1030

Any supported ones *useful* for users that I'm missing?

2021-06-14 14:20 UTC, TheTripleV requested changes

2021-06-14 14:20 UTC, TheTripleV commented on source/docs/software/advanced-gradlerio/gradlew-tasks.rst
> +``./gradlew generateCompileCommands`` - Generate compile_commands.json. This is a configuration file that is supported by many Integated Development Environments.
Integated -> Integrated

2021-06-19 17:31 UTC, AustinShalit commented on source/docs/software/advanced-gradlerio/gradlew-tasks.rst
> +----------
```suggestion
Build tasks
-----------
```

2021-06-30 02:28 UTC, ThadHouse approved these changes

2021-06-30 02:53 UTC, merged