Add additional Romi Hardware information
wpilibsuite/frc-docs pull request #1386
Opened 2021-07-04 02:52 UTC by Daltz333

I made Romi Hardware information into a separate document, as I'd like to hopefully expand on it more in the future.

2021-07-09 00:38 UTC, zhiquanyeo requested changes

2021-07-09 00:38 UTC, zhiquanyeo commented on source/docs/romi-robot/getting-to-know-romi.rst
> +Analog Input
```suggestion
Analog Input (Default Configuration)
```

2021-07-09 00:38 UTC, zhiquanyeo commented on source/docs/romi-robot/getting-to-know-romi.rst
> +| PWM 2       | Pin 21 / A3             |
We should specify that this specific pin mapping is the default configuration, and that it can be configured via the web UI

2021-07-09 00:38 UTC, zhiquanyeo commented on source/docs/romi-robot/hardware-support.rst
> +The Romi robot has limited hardware interfacing support. It is not compatible with the large majority of FRC based control system components. Details on the pin mapping is available in :doc:`getting-
```suggestion
The Romi robot, having a different hardware architecture as a roboRIO, is compatible with a subset of commonly used FRC control system components.

Compatible Hardware
------------------------

In general, the Romi is compatible with the following:

- Simple Digital Input/Output devices (e.g. bumper switches, single LEDs)
- Standard RC-style PWM output devices (e.g. servos, PWM based motor controllers)
- Analog Input sensors (e.g distance sensors that report distance as a voltage)
```

2021-07-09 00:38 UTC, zhiquanyeo commented on source/docs/romi-robot/hardware-support.rst
> +The Romi Robot DIO is not compatible with the following:
```suggestion
Due to hardware limitations, the Romi Robot is not compatible with the following:
```

2021-07-09 00:38 UTC, zhiquanyeo commented on source/docs/romi-robot/hardware-support.rst
> +- Ultrasonics
```suggestion
- "Ping" style ultrasonic sensors (which require 2 DIO channels)
```

2021-07-09 00:38 UTC, zhiquanyeo commented on source/docs/romi-robot/hardware-support.rst
> +- Timing based sensors
```suggestion
- Timing based sensors
- CAN based devices
```

2021-07-09 01:23 UTC, Daltz333 commented on source/docs/romi-robot/getting-to-know-romi.rst
> +^^^^^^^^^^^^
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2021-07-15 22:20 UTC, zhiquanyeo requested changes
Minor nits, but otherwise LGTM

2021-07-15 22:20 UTC, zhiquanyeo commented on source/docs/romi-robot/getting-to-know-romi.rst
> +The table below shows the default pins. These are configurable via the Web UI.
```suggestion
The table below shows the default pins. These are configurable (with the exception of PWM 0 and 1) via the Web UI.
```

2021-07-15 22:20 UTC, zhiquanyeo commented on source/docs/romi-robot/hardware-support.rst
> +- Non-integrated encoders
```suggestion
- Encoders other than the Romi-integrated encoders
```

2021-07-16 01:04 UTC, zhiquanyeo submitted a review, later dismissed
LGTM

2021-07-16 01:16 UTC, jasondaming approved these changes

2021-07-16 17:19 UTC, merged