Update SysId Encoder docs
wpilibsuite/frc-docs pull request #1506
Opened 2021-10-31 03:48 UTC by Piphi5

Fixes #1469

2021-10-31 03:57 UTC, calcmogul commented on source/docs/software/pathplanning/robot-characterization/configuring-project.rst
> +The :guilabel:`Encoder Selection` allows you to configure the encoders that will be used. The types of encoder you can use will vary with the first motor controller type specified (see note :ref:`abo
```suggestion
The :guilabel:`Encoder Selection` allows you to configure the encoders that will be used. The types of encoder you can use will vary with the first motor controller type specified (see note :ref:`above <docs/software/pathplanning/robot-characterization/configuring-project:Motor Controller Selection>`). However, there are two types that are consistent across all motor controller selections: ``roboRIO`` which corresponds to any encoders that are plugged into the rio, ``CANCoder`` which corresponds to the CTRE CANCoder. If you are using a TalonSRX or TalonFX for your motor controller, the ``Built-In`` corresponds to any quadrature encoder plugged into the encoder port and the ``Tachometer`` option corresponds to the CTRE Tachometer plugged into the port. If you're using a Spark MAX, the ``Encoder Port`` refers to an encoder plugged into the :ref:`encoder port <https://docs.revrobotics.com/sparkmax/feature-description/encoder-port>` and the ``Data Port`` refers to an encoder plugged into the :ref:`data port <https://docs.revrobotics.com/sparkmax/feature-description/data-port>`. For the Venom, `Built-in` refers to an encoder plugged into the Venom's encoder port.
```

2021-10-31 04:31 UTC, calcmogul approved these changes

2021-10-31 04:48 UTC, Daltz333 commented on source/docs/software/pathplanning/robot-characterization/configuring-project.rst
> +The :guilabel:`Encoder Selection` allows you to configure the encoders that will be used. The types of encoder you can use will vary with the first motor controller type specified (see note :ref:`abo
I think the latter part of this paragraph can get broken up into a list

2021-11-01 03:27 UTC, calcmogul requested changes

2021-11-01 03:27 UTC, calcmogul commented on source/docs/software/pathplanning/robot-characterization/configuring-project.rst
> +- **General Types** (consistent across all motor controller selections): ``roboRIO`` corresponds to any encoders that are plugged into the rio, ``CANCoder`` corresponds to the CTRE CANCoder.
```suggestion
- **General Types** (consistent across all motor controller selections): ``roboRIO`` corresponds to any encoders that are plugged into the roboRIO, ``CANCoder`` corresponds to the CTRE CANCoder.
```

2021-11-01 05:07 UTC, calcmogul requested changes

2021-11-01 05:07 UTC, calcmogul commented on source/docs/software/pathplanning/robot-characterization/configuring-project.rst
> +- **TalonSRX** or **TalonFX**: ``Built-in`` corresponds to any quadrature encoder plugged into the encoder port, ``Tachometer`` corresponds to the CTRE Tachometer plugged into the encoder port.
The built-in encoder for the Talon FX isn't actually a quadrature encoder.
```cpp
  if (encoderType == "Built-in") {
    if (starts_with(controllerName, "Talon")) {
      FeedbackDevice feedbackDevice;
      if (controllerName == "TalonSRX") {
        feedbackDevice = FeedbackDevice::QuadEncoder;
      } else {
        feedbackDevice = FeedbackDevice::IntegratedSensor;
      }
```

2021-11-02 06:28 UTC, calcmogul submitted a review, later dismissed

2021-11-02 20:46 UTC, prateekma approved these changes

2021-11-03 03:07 UTC, Daltz333 approved these changes

2021-11-03 03:07 UTC, Daltz333 requested changes

2021-11-03 03:07 UTC, Daltz333 commented on source/docs/software/pathplanning/robot-characterization/configuring-project.rst
> +"""""""""""""
```suggestion
~~~~~~~~~~~~~
```

2021-11-03 03:08 UTC, Daltz333 commented on source/docs/software/pathplanning/robot-characterization/configuring-project.rst
> +"""""""""""""
We should not have more than 4 layers of depth, it is bad flow.

2021-11-04 15:21 UTC, Piphi5 commented
Are there any changes that need to be made before this is merged?

2021-11-04 15:24 UTC, Daltz333 approved these changes

2021-11-04 15:24 UTC, merged