Third Party Examples
wpilibsuite/frc-docs pull request #1519
Opened 2021-11-13 19:15 UTC by jasondaming

Closes #1515

2021-11-13 19:26 UTC, sciencewhiz commented
I'm thinking it makes more sense to integrate into the 3rd party libraries article rather then having a separate examples article that someone has to discover.

2021-11-20 03:25 UTC, Daltz333 requested changes

2021-11-20 03:25 UTC, Daltz333 commented on source/docs/software/examples-tutorials/third-party-examples.rst
> +* `Swerve Drive Specialties (SDS) <https://github.com/SwerveDriveSpecialties/swerve-template>`__
Should we sort alphabetically?

2021-11-20 03:25 UTC, Daltz333 commented on source/docs/software/examples-tutorials/third-party-examples.rst
> +* `Limelight <https://docs.limelightvision.io/en/latest/cs_drive_to_goal_2019.html>`__ (more case studies can be found on the left)
```suggestion
* `Limelight <https://docs.limelightvision.io/en/latest/cs_drive_to_goal_2019.html>`__ (more case studies can be found on the left)
```

As a reader, I don't know what "more" is really referring to as there is no noun that it was previously describing. Also the reader has no idea what a "case study" is. I'd either omit this entire sentence or rephrase to something close to "example code can be found in the left menu in the form of case studies", but that is quite lengthy.

2021-11-20 14:06 UTC, jasondaming commented on source/docs/software/examples-tutorials/third-party-examples.rst
> +* `Swerve Drive Specialties (SDS) <https://github.com/SwerveDriveSpecialties/swerve-template>`__
done

2021-12-11 23:19 UTC, Daltz333 approved these changes

2021-12-11 23:19 UTC, merged