Update Radio Programming for 2022
wpilibsuite/frc-docs pull request #1600
Opened 2022-01-04 21:05 UTC by Kevin-OConnor

Updates for 2022 and addresses some feedback from Beta.

2022-01-04 21:06 UTC, Daltz333 submitted a review, later dismissed

2022-01-04 21:44 UTC, sciencewhiz commented
Similar changes should be made to programming-radios-for-fms-offseason

2022-01-05 16:11 UTC, Daltz333 requested changes

2022-01-05 16:11 UTC, Daltz333 commented on source/docs/software/driverstation/programming-radios-for-fms-offseason.rst
> +#. Plug directly from your computer into the wireless bridge ethernet port closest to the power jack and make sure no other devices are connected to your computer via ethernet. If powering the radio
```suggestion
#. Plug directly from your computer into the wireless bridge ethernet port closest to the power jack. Make sure no other devices are connected to your computer via ethernet. If powering the radio via PoE, plug an Ethernet cable from the PC into the socket side of the PoE adapter (where the roboRIO would plug in). If you experience issues configuring through the PoE adapter, you may try connecting the PC to the alternate port on the radio.
```

2022-01-05 16:11 UTC, Daltz333 commented on source/docs/software/driverstation/programming-radios-for-fms-offseason.rst
> +#. Plug directly from your computer into the wireless bridge ethernet port closest to the power jack and make sure no other devices are connected to your computer via ethernet. If powering the radio
I think having them as two separate sentences reads a bit better.

2022-01-05 16:11 UTC, Daltz333 commented on source/docs/zero-to-robot/step-3/radio-programming.rst
> +2. Plug directly from your computer into the wireless bridge ethernet port closest to the power jack and make sure no other devices are connected to your computer via ethernet. If powering the radio
```suggestion
2. Plug directly from your computer into the wireless bridge ethernet port closest to the power jack. Make sure no other devices are connected to your computer via ethernet. If powering the radio via PoE, plug an Ethernet cable from the PC into the socket side of the PoE adapter (where the roboRIO would plug in). If you experience issues configuring through the PoE adapter, you may try connecting the PC to the alternate port on the radio.
```

2022-01-05 17:22 UTC, merged