angle wrap example with LQR
wpilibsuite/frc-docs pull request #1798
Opened 2022-04-16 02:34 UTC by jasondaming

Closes #1786

2022-04-16 06:26 UTC, calcmogul requested changes
Otherwise looks good.

2022-04-16 06:26 UTC, calcmogul commented on source/docs/software/advanced-controls/state-space/state-space-flywheel-walkthrough.rst
> +         auto error = lqr.R() - x;
```suggestion
         Eigen::Vector<double, 2> error = lqr.R() - x;
```

2022-04-16 19:01 UTC, calcmogul approved these changes

2022-04-16 19:05 UTC, Starlight220 commented
Maybe this is something that should be added to the API docs as well?

2022-04-18 13:03 UTC, Daltz333 approved these changes

2022-04-18 13:03 UTC, merged