Add EventLoop article
wpilibsuite/frc-docs pull request #1827
Opened 2022-05-15 17:34 UTC by Starlight220

Corresponding to wpilibsuite/allwpilib#4104.

2022-05-15 19:55 UTC, Daltz333 requested changes
Can we link to a more complete usage example anywhere?

2022-05-15 19:55 UTC, Daltz333 commented on source/docs/software/convenience-features/event-based.rst
> +rising() / Rising(), falling() / Falling()
We can just default to the Java naming for verbosity sake.

2022-06-10 10:20 UTC, Starlight220 commented
The corresponding allwpilib PR was merged, this can be too.

2022-06-14 02:17 UTC, Daltz333 approved these changes

2022-06-14 02:17 UTC, merged