Fix documentation error
wpilibsuite/frc-docs pull request #1903
Opened 2022-09-10 08:35 UTC by rwlee

`IdentifyDrivetrainSystem` currently has 2 overloads https://first.wpi.edu/wpilib/allwpilib/docs/release/cpp/classfrc_1_1_linear_system_id.html#a683b6de8c6a77b64329f0184b8f2bff2 -- they use inconsistent types and the example given has types consistent with the 5 argument overload. It is very possible that the 4 argument version is just using the wrong units and should be changed to match the example instead.

2022-09-10 08:37 UTC, rwlee commented
https://github.com/wpilibsuite/allwpilib/blob/main/wpimath/src/main/native/cpp/system/plant/LinearSystemId.cpp#L56 -- the alternative is changing line 56 and the associated function

2022-09-11 00:07 UTC, calcmogul requested changes
By the way, `KitbotWheelSize.SixInch` in a Java example below this change is also incorrect. It should be `KitbotWheelSize.kSixInch`.

2022-09-11 00:07 UTC, calcmogul commented on source/docs/software/wpilib-tools/robot-simulation/drivesim-tutorial/drivetrain-model.rst
> +      static constexpr auto TrackWidth = 0.7112_m;
```suggestion
      static constexpr auto kTrackwidth = 0.7112_m;
```

2022-09-11 00:07 UTC, calcmogul commented on source/docs/software/wpilib-tools/robot-simulation/drivesim-tutorial/drivetrain-model.rst
> +        TrackWidth,
```suggestion
          KvLinear, KaLinear, KvAngular, KaAngular, kTrackWidth),
        kTrackWidth,
```

2022-09-13 19:46 UTC, calcmogul requested changes

2022-09-13 19:46 UTC, calcmogul commented on source/docs/software/wpilib-tools/robot-simulation/drivesim-tutorial/drivetrain-model.rst
> +        KitbotWheelSize.kSixInch,     // 6" diameter wheels.
```suggestion
        KitbotWheelSize.kSixInch,    // 6" diameter wheels.
```

2022-09-18 23:52 UTC, Daltz333 approved these changes

2022-09-18 23:52 UTC, merged