Fix robot code CI examples
wpilibsuite/frc-docs pull request #2052
Opened 2022-12-24 16:53 UTC by brennenputh

The current robot code CI example is broken due to [this Github Actions issue](https://github.com/actions/runner/issues/2033).  This PR adds a fix to the example CI to avoid this issue.

2022-12-24 22:24 UTC, auscompgeek submitted a review, later dismissed
LGTM. allwpilib uses the same workaround since CI runs in Docker there too.

2022-12-24 22:24 UTC, auscompgeek commented on source/docs/software/advanced-gradlerio/robot-code-ci.rst
> +Each job has certain steps that will be executed. This job has four steps. The first step involves checking out the repository to access the robot code. The second step is a workaround for a `GitHub
GitHub canonical URLs don't have `www.`
```suggestion
Each job has certain steps that will be executed. This job has four steps. The first step involves checking out the repository to access the robot code. The second step is a workaround for a `GitHub Actions issue <https://github.com/actions/runner/issues/2033>`_. The third step involves giving the virtual machine permission to execute gradle tasks using ``./gradlew``. The final step runs ``./gradlew build`` to compile robot code and run any unit tests.
```

2022-12-25 16:36 UTC, Daltz333 requested changes

2022-12-25 16:36 UTC, Daltz333 commented on source/docs/software/advanced-gradlerio/robot-code-ci.rst
> +Each job has certain steps that will be executed. This job has four steps. The first step involves checking out the repository to access the robot code. The second step is a workaround for a `GitHub
```suggestion
Each job has certain steps that will be executed. This job has four steps. The first step involves checking out the repository to access the robot code. The second step is a workaround for a `GitHub Actions issue <https://github.com/actions/runner/issues/2033>`__. The third step involves giving the virtual machine permission to execute gradle tasks using ``./gradlew``. The final step runs ``./gradlew build`` to compile robot code and run any unit tests.
```

2022-12-25 20:04 UTC, Daltz333 approved these changes

2022-12-25 20:04 UTC, merged