Update shuffleboard-lists.rst
wpilibsuite/frc-docs pull request #2202
Opened 2023-02-21 21:19 UTC by sendhelpidfk

There were some errors (especially relative to the current version of Shuffleboard), so I rewrote a good amount of the page. I think I caught most of the major ones, but I could be wrong.

As someone with ADHD, I also marked some of the denser sections to be easier to follow at a glance for myself, particularly 'Rearranging tiles in a list'. The style guide, as far as I can tell, doesn't conflict with this, and it makes it easier to read and parse in general.

If I have time later during this season, I'll try my hand at rewriting more of this section in a similar manner (if this style of writing isn't missing something critical).

2023-02-22 04:08 UTC, Starlight220 commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +- **"Move up"** moves the tile **towards** the *top* of the list.
Perhaps use :guilabel: for indicating GUI labels?
For example:
```suggestion
- :guilabel:`Move up` moves the tile **towards** the *top* of the list.
```

2023-02-22 05:23 UTC, sciencewhiz requested changes

2023-02-22 05:23 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +A tile can be **added** to an existing list as follows:
```suggestion
A tile can be **added** to an existing list as follows:
```

2023-02-22 05:23 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +1. Identify the list and the tile to be added.
```suggestion
1. Identify the list and the tile to be added.
```

2023-02-22 05:23 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
>  ----------------------
The underline needs to match the length of the title

2023-04-01 01:13 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
>  ----------------------
```suggestion
------------------------------------------
```

2023-04-01 01:18 UTC, sciencewhiz reviewed
more guilabels

2023-04-01 01:18 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +- **"Move down"** moves the tile **towards** the *bottom* of the list.
```suggestion
-:guilabel`Move down` moves the tile **towards** the *bottom* of the list.
```

2023-04-01 01:18 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +- **"Send to top"** moves the tile **to** the *top* of a list.
```suggestion
- :guilabel:`Send to top` moves the tile **to** the *top* of a list.
```

2023-04-01 01:18 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +- **"Send to bottom"** moves the tile **to** the *bottom* of a list.
```suggestion
-::guilabel:`Send to bottom` moves the tile **to** the *bottom* of a list.
```

2023-04-01 01:18 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +   - The **top "Remove"** button (above the pinline; section of dropdown with grayed-out *tile* label) **deletes** the *tile* from the Shuffleboard layout.
```suggestion
   - The **top** :guilabel:Remove` button (above the pinline; section of dropdown with grayed-out *tile* label) **deletes** the *tile* from the Shuffleboard layout.
```

2023-04-01 01:18 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +- There are two buttons labeled *"Remove"*, and each button does:
```suggestion
- There are two buttons labeled :guilabel:`Remove`, and each button does:
```

2023-04-01 01:18 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +   - The **bottom "Remove"** button (below the pinline; section of dropdown with grayed-out *list* label) **deletes** the *list and all tiles inside it* from the Shuffleboard layout.
```suggestion
   - The **bottom** :guilabel:`Remove` button (below the pinline; section of dropdown with grayed-out *list* label) **deletes** the *list and all tiles inside it* from the Shuffleboard layout.
```

2023-04-01 01:23 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +1. Identify the list and the tile within it to be removed.
```suggestion
1. Identify the list and the tile within it to be removed.
```

2023-04-01 01:29 UTC, sciencewhiz reviewed
more linting fixes

2023-04-01 01:29 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +-:guilabel`Move down` moves the tile **towards** the *bottom* of the list.
```suggestion
- :guilabel`Move down` moves the tile **towards** the *bottom* of the list.
```

2023-04-01 01:29 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +   - The **top** :guilabel:Remove` button (above the pinline; section of dropdown with grayed-out *tile* label) **deletes** the *tile* from the Shuffleboard layout.
```suggestion

   - The **top** :guilabel:Remove` button (above the pinline; section of dropdown with grayed-out *tile* label) **deletes** the *tile* from the Shuffleboard layout.
```

2023-04-01 01:34 UTC, sciencewhiz reviewed
more formatting

2023-04-01 01:34 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +-::guilabel:`Send to bottom` moves the tile **to** the *bottom* of a list.
```suggestion
- :guilabel:`Send to bottom` moves the tile **to** the *bottom* of a list.
```

2023-04-01 01:34 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +- :guilabel`Move down` moves the tile **towards** the *bottom* of the list.
```suggestion
- :guilabel:`Move down` moves the tile **towards** the *bottom* of the list.
```

2023-04-01 01:34 UTC, sciencewhiz commented on source/docs/software/dashboards/shuffleboard/getting-started/shuffleboard-lists.rst
> +   - The **top** :guilabel:Remove` button (above the pinline; section of dropdown with grayed-out *tile* label) **deletes** the *tile* from the Shuffleboard layout.
```suggestion
   - The **top** :guilabel:`Remove` button (above the pinline; section of dropdown with grayed-out *tile* label) **deletes** the *tile* from the Shuffleboard layout.
```

2023-04-01 01:39 UTC, sciencewhiz approved these changes

2023-04-01 23:31 UTC, merged