Add note about smartscreen warning during install docs
wpilibsuite/frc-docs pull request #2203
Opened 2023-02-22 03:27 UTC by rzblue

2023-02-22 03:29 UTC, Daltz333 commented on source/docs/zero-to-robot/step-2/wpilib-setup.rst
> +      .. note:: After launching the installer, Windows may display a window titled "Windows protected your PC". Click "More info" to reveal a "Run anyway" button that will allow you to run the instal
Replace references to buttons with :guilabel:

2023-02-22 04:02 UTC, Starlight220 requested changes

2023-02-22 04:02 UTC, Starlight220 commented on source/docs/zero-to-robot/step-2/wpilib-setup.rst
> +      .. note:: After launching the installer, Windows may display a window titled "Windows protected your PC". Click :guilabel:`More info`, then select :guilabel:`Run anyway` run the installer.
```suggestion
      .. note:: After launching the installer, Windows may display a window titled "Windows protected your PC". Click :guilabel:`More info`, then select :guilabel:`Run anyway` to run the installer.
```

2023-02-22 05:06 UTC, Starlight220 commented on source/docs/zero-to-robot/step-2/wpilib-setup.rst
> +      After opening the .iso file, launch the installer by opening ``WPILibInstaller.exe``.
```suggestion
      After opening the ``.iso`` file, launch the installer by opening ``WPILibInstaller.exe``.
```

2023-02-22 10:07 UTC, Starlight220 approved these changes

2023-02-23 03:15 UTC, sciencewhiz approved these changes

2023-02-23 05:32 UTC, merged