Rename benchtop and wire FRC robot pages
wpilibsuite/frc-docs pull request #2238
Opened 2023-04-04 04:05 UTC by sciencewhiz

Wiring an FRC robot only covered drivetrain, rename to wiring simple FRC Robot Drivetrain
Benchtop was confusing since it's actually a drivetrain 
Fixes #2020

2023-04-04 14:33 UTC, Starlight220 requested changes
I don't see value in adding "Simple" to the title; I'd expect an example to be simple regardless. In addition, this opens room for speculation whether wiring a not-"simple" robot is any different.

2023-04-05 04:02 UTC, sciencewhiz commented
Ultimately, the article doesn't do justice on how to wire an FRC robot, and shouldn't advertise that. I'm open to other ideas for titles.

2023-04-07 01:34 UTC, sciencewhiz commented
@Daltz333 suggested Intro to Wiring

2023-04-10 03:56 UTC, Daltz333 approved these changes

2023-04-27 19:44 UTC, merged