Add c++ counterparts for java shuffleboard snippets
wpilibsuite/frc-docs pull request #2299
Opened 2023-07-23 02:47 UTC by cfinn68916

2023-07-23 05:07 UTC, Starlight220 requested changes

2023-07-23 05:07 UTC, Starlight220 commented on source/docs/software/dashboards/shuffleboard/layouts-with-code/sending-data.rst
> +            .AddPersistent("Sendable Title", mySendable);
These strings should match the ones in the Java snippet.

2023-07-23 19:24 UTC, calcmogul requested changes

2023-07-23 19:24 UTC, calcmogul commented on source/docs/software/dashboards/shuffleboard/layouts-with-code/sending-data.rst
> +            .add("Sendable Title", mySendable);
```suggestion
            .Add("Sendable Title", mySendable);
```

2023-07-24 05:02 UTC, Starlight220 reviewed
Should we namespace-qualify here? What do we do usually?

2023-07-24 05:49 UTC, calcmogul commented
The WPILib examples include the `frc::` prefix.

2023-07-24 15:48 UTC, Starlight220 commented
So yeah, stuff here should be qualified with the `frc::` prefix.

2023-07-29 00:03 UTC, cfinn68916 commented
Can you sqaush the PR when you merge?

2023-07-29 00:06 UTC, sciencewhiz commented
Don't worry, we squash by default, unless there's a reason not to.

2023-07-29 02:14 UTC, sciencewhiz approved these changes

2023-08-01 04:16 UTC, merged