Update TrapezoidProfile docs
wpilibsuite/frc-docs pull request #2301
Opened 2023-07-24 03:29 UTC by Gold856

2023-08-01 04:16 UTC, Daltz333 commented
@calcmogul can you review this when you got a chance?

2023-08-01 04:20 UTC, calcmogul requested changes

2023-08-01 04:20 UTC, calcmogul commented on source/docs/software/advanced-controls/controllers/trapezoidal-profiles.rst
> +Now that we know how to create a set of constraints and the desired start/end states, we are ready to create our motion profile.  The ``TrapezoidProfile`` constructor takes 1 parameter; the constrain
```suggestion
Now that we know how to create a set of constraints and the desired start/end states, we are ready to create our motion profile.  The ``TrapezoidProfile`` constructor takes 1 parameter: the constraints.
```

2023-08-01 04:50 UTC, calcmogul approved these changes

2023-08-03 03:04 UTC, Daltz333 approved these changes

2023-08-03 03:04 UTC, merged