use new tabs
wpilibsuite/frc-docs pull request #2363
Opened 2023-10-24 01:14 UTC by GrahamSH-LLK

incomplete, I still have 34 files to go
however the first portion is done and I'm heading to bed

2023-10-25 04:01 UTC, sciencewhiz requested changes

2023-10-25 10:49 UTC, GrahamSH-LLK commented on source/docs/contributing/frc-docs/style-guide.rst
> +.. tab-set-code::
yep i fixed that locally but haven't pushed yet. thanks!

2023-10-25 22:02 UTC, GrahamSH-LLK commented
Should be done/ ready for review

2023-10-26 21:34 UTC, sciencewhiz commented
It would be good to add something to the style guide about how to use tabs. It's not there now, but since the methods are changing I think it makes sense to document now

2023-10-27 04:50 UTC, Daltz333 commented
Do the `tab-set-code` actually sync across all tabs across a page?

2023-10-27 04:55 UTC, sciencewhiz commented
I had tested a few and they did, but I haven't tried multiple browsers

2023-10-28 20:06 UTC, sciencewhiz commented
sphinx-tabs can be removed as a dependency for poetry, right?

2023-10-29 18:25 UTC, GrahamSH-LLK commented
> sphinx-tabs can be removed as a dependency for poetry, right?

yes

2023-10-30 17:58 UTC, GrahamSH-LLK commented
I added to style guide and fixed the conflicts

2023-11-03 04:22 UTC, Daltz333 approved these changes

2023-11-03 04:22 UTC, merged