updated git metadata docs page based on akit docs
wpilibsuite/frc-docs pull request #2366
Opened 2023-10-26 21:53 UTC by Lewis-Seiden

2023-10-26 22:37 UTC, rzblue requested changes
Needs some formatting changes and clarifications

This should also include an example of the generated class and how to use it

2023-10-26 22:37 UTC, rzblue commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> +- Installing gversion
This should be a heading

2023-10-26 22:37 UTC, rzblue commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> +To install gversion add the following line to the plugins block of `build.gradle`.
```suggestion
To install gversion add the following line to the plugins block of ``build.gradle``.
```
Inline code blocks use 2 backticks

2023-10-26 22:37 UTC, rzblue commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> +Then add the following block to `build.gradle` to add `createVersionFile` as a dependancy of `compileJava`. The `timeZone` field can be modified based on your team's time zone based on `this list of
Explain what this does- similar to the previous contents that said "This registers a Gradle task that uses the above Git command...."

2023-10-26 22:37 UTC, rzblue commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> -  ...
This should stay with changes to make it make sense

2023-10-27 17:18 UTC, Daltz333 requested changes

2023-10-27 17:18 UTC, Daltz333 commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> +To test this run a build of your project by clicking the WPILib logo in the top right of VS Code and searching for "Build Robot Code". Once the build has finished running there should be a file calle
There is a run-on sentence and the sentence doesn't read well. Can you rephrase it?

2023-10-27 17:18 UTC, Daltz333 commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> +Since these files include data that is already tracked by Git and are regenerated every time code is deployed, it is recommended to not track these changes with Git by using the `gitignore <https://g
The language here is pretty stiff.

2023-10-27 17:18 UTC, Daltz333 commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> +Next we need to tell gradle to make the file containing our git data when we build the project. To do that add the following block to ``build.gradle``, which adds ``createVersionFile`` as a dependenc
We should avoid "we".

2023-10-28 00:30 UTC, sciencewhiz commented
Does this address #2182?

2023-11-16 05:27 UTC, Daltz333 requested changes

2023-11-16 05:27 UTC, Daltz333 commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> +To install gversion add the following line to the plugins block of ``build.gradle``. This tells Gradle to use gversion in the project.
Punctuation needs to be added here

2023-11-16 05:27 UTC, Daltz333 commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> +In order to generate the file when building the project, add the following block to the bottom or otherwise at the root of ``build.gradle``.
I think the latter fragment "otherwise..." Is unnecessary

2023-11-16 05:27 UTC, Daltz333 commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> +To test this run a build of your project by clicking the WPILib logo in the top right of VS Code and selecting the "Build Robot Code" option. Once the code has finished building, there should be a fi
Run on sentence here

2023-11-16 05:52 UTC, Lewis-Seiden commented on source/docs/software/advanced-gradlerio/deploy-git-data.rst
> +To install gversion add the following line to the plugins block of ``build.gradle``. This tells Gradle to use gversion in the project.
what punctuation is missing?

2023-12-29 07:18 UTC, Starlight220 reviewed
How does this behave if the project isn't stored in git?

2024-01-02 02:48 UTC, Lewis-Seiden commented
> How does this behave if the project isn't stored in git?

it generates `BuildConstants.java` with most fields set to a "not found" or default value

2024-01-03 04:14 UTC, jasondaming commented
It looks good enough to me but I am not the grammar....expert.

2024-01-05 22:58 UTC, Daltz333 approved these changes

2024-01-05 22:59 UTC, merged