Update AdvantageScope docs
wpilibsuite/frc-docs pull request #2418
Opened 2023-12-06 01:52 UTC by jwbonner

These updates reflect AdvantageScope's inclusion in the WPILib installer for 2024, with a dedicated page and references from relevant locations in the rest of the docs. The idea is to keep the main AdvantageScope docs separate but make the tool more discoverable.

I think the main questions here relate to organization. The AdvantageScope is page under "Telemetry" in this version, but I could see arguments for putting it under "Dashboard" (with Glass, which is also programmer's tool) or "Software Tools" (with OutlineViewer). I also added AdvantageScope references to the pages for Field2d, Mechanism2d, and plots; these are currently organized under "Glass", but the Field2d and plots pages are also part of "Robot Simulation" where I think the inclusion of AdvantageScope makes more sense. There's a bit of a disconnect now between those features and Glass, but maybe keeping AdvantageScope as a side reference on those pages is an OK solution? I'm open to suggestions.

I'm opening this as a draft for now since the explanation for how to open AdvantageScope won't actually work until it's included in the tools menu and file associations are added for Windows.

2023-12-08 16:21 UTC, jasondaming requested changes
Good stuff I think we should merge this ASAP with a couple changes.

We can defer this to a different PR if you want but I really thing we should have a section on publishing swerve states (I don't remember the current state of structs?).  For troubleshooting and getting started with Swerve this is one of the most helpful things teams can do

2023-12-11 04:56 UTC, jwbonner commented
A few changes:

- I split the DataLog page in two to address #2422, with sections for AdvantageScope and the DataLogTool. Another section for the DS could be added there in the future.
- Based on the changes in #2428, I moved the main AdvantageScope page to "Dashboards". I think this fits better since the new data log download page mentions AdvantageScope already.
- I added a section to the swerve drive kinematics page for AdvantageScope, which seemed like the most obvious place to talk about swerve visualization since the `SwerveModuleState` class is introduced on that page. There is example code for publishing the states to NT in Java and C++. Python should also be included, I just haven't had a chance to figure out how struct publishing works for that.

2023-12-11 13:48 UTC, jasondaming commented
I am not sure struct publishing is done for python.  At least I couldn't [find it](https://robotpy.readthedocs.io/projects/pyntcore/en/stable/ntcore.html).

@virtuald do you know how we would do this?

2023-12-11 18:20 UTC, virtuald commented
It is not implemented yet: https://github.com/robotpy/mostrobotpy/issues/5

2023-12-14 13:49 UTC, jasondaming commented
I don't think there is anything preventing this from being merged with a little cleanup.

2023-12-14 16:56 UTC, jwbonner commented on source/docs/software/telemetry/advantagescope.rst
> +.. note:: Detailed documentation for AdvantageScope can be found `here <https://github.com/Mechanical-Advantage/AdvantageScope/blob/main/docs/INDEX.md>`__. It is also available offline by clicking th
This note is now moved near the top, above the screenshot and list of features.

2023-12-14 17:47 UTC, jasondaming approved these changes

2023-12-14 17:47 UTC, merged

2023-12-31 05:31 UTC, virtuald commented
FWIW python struct publishing is now merged: https://github.com/robotpy/mostrobotpy/pull/50