Adding Python to swerve kinematics and odometry
wpilibsuite/frc-docs pull request #2434
Opened 2023-12-11 23:11 UTC by jasondaming

I find it odd that the first example uses the m_ notation, but the rest of the examples (which often "depend" on the kinematics object) do not use that variable naming.  I think we should standardize but wanted to have agreement and direction.

Waiting on the swervebot example in Python to be done also.

2023-12-12 07:00 UTC, virtuald requested changes

2023-12-12 07:00 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/swerve-drive-odometry.rst
> +      m_frontLeftLocation = Translation2d(0.381, 0.381)
I would put these all in

```
class MyRobot:
  def robotInit(self):
    self.frontLeftLocation = ...
```

2023-12-14 18:42 UTC, virtuald approved these changes

2023-12-23 19:48 UTC, sciencewhiz submitted a review, later dismissed

2024-01-01 20:37 UTC, sciencewhiz approved these changes

2024-01-01 20:37 UTC, merged