Add Python to mecanum kinematics and odometry
wpilibsuite/frc-docs pull request #2435
Opened 2023-12-11 23:12 UTC by jasondaming

I find it odd that the first example uses the m_ notation, but the rest of the examples (which often "depend" on the kinematics object) do not use that variable naming. I think we should standardize but wanted to have agreement and direction.

Waiting on the mecanumbot example in Python to be done also.

2023-12-12 06:57 UTC, virtuald requested changes

2023-12-12 06:57 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/mecanum-drive-kinematics.rst
> +      m_frontLeftLocation = Translation2d(0.381, 0.381)
Python should not use `m_` notation. Do `self.name` or just `name` if not in a function.

2023-12-12 06:57 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/mecanum-drive-odometry.rst
> +        m_pose = m_odometry.update(gyroAngle, wheelPositions)
self.pose

2023-12-12 19:57 UTC, virtuald requested changes

2023-12-12 19:57 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/mecanum-drive-kinematics.rst
> +      double forward = chassisSpeeds.vx
double isn't needed

2023-12-12 19:57 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/mecanum-drive-odometry.rst
> +      odometry = MecanumDriveOdometry(
self.odometry?

2023-12-12 19:57 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/mecanum-drive-odometry.rst
> +        gyroAngle = gyro.getRotation2d()
self.gyro, self.frontLeftEncoder..

2023-12-12 19:57 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/mecanum-drive-odometry.rst
> +        self.pose = odometry.update(gyroAngle, wheelPositions)
self.odometry

2023-12-14 18:54 UTC, virtuald approved these changes

2023-12-23 19:49 UTC, sciencewhiz approved these changes

2023-12-24 04:39 UTC, merged