Add Python Example to Swerve Visualization Struct
wpilibsuite/frc-docs pull request #2471
Opened 2024-01-01 17:11 UTC by jasondaming

@virtuald can you correct this example.  I am not sure how exactly to use this struct.  Hopefully I got this close?

2024-01-01 20:11 UTC, virtuald requested changes
For future struct topic, refer to the tests at https://github.com/robotpy/mostrobotpy/blob/main/subprojects/pyntcore/tests/test_struct_topic.py

2024-01-01 20:11 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/swerve-drive-kinematics.rst
> +      class MyStruct:
This isn't part of this example

2024-01-01 20:11 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/swerve-drive-kinematics.rst
> +      from wpiutil import wpistruct
This import isn't required for this example

2024-01-01 20:11 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/swerve-drive-kinematics.rst
> +      topic = nt.getStructArrayTopic("/SwerveStates", SwerveModuleState.struct)
`.struct` isn't needed, should be `topic = nt.getStructArrayTopic("/SwerveStates", SwerveModuleState)`

2024-01-01 20:11 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/swerve-drive-kinematics.rst
> +        self.pub.set(MyStruct(frontLeftState,frontRightState,backLeftState,backRightState))
`SwerveModuleState`, not `MyStruct`

2024-01-01 22:05 UTC, virtuald commented on source/docs/software/kinematics-and-odometry/swerve-drive-kinematics.rst
> +        self.pub.set(SwerveModuleState(frontLeftState,frontRightState,backLeftState,backRightState))
Oh, you're right, this should be `self.pub.set([frontLeftState,frontRightState,backLeftState,backRightState])`

2024-01-06 04:11 UTC, sciencewhiz approved these changes

2024-01-06 04:11 UTC, merged