Document generateCompileCommands task better
wpilibsuite/frc-docs pull request #2582
Opened 2024-02-22 02:58 UTC by spacey-sooty

includes a warning about not being reccomended for most users

2024-02-22 03:36 UTC, spacey-sooty commented
\inspector fix all

2024-03-07 20:05 UTC, rzblue requested changes

2024-03-07 20:05 UTC, rzblue commented on source/docs/software/advanced-gradlerio/gradlew-tasks.rst
> +    Using compile commands isn't recommended for most users and has a variety of pitfalls compared to in built intellisense.
```suggestion
    Using compile commands isn't recommended for most users and has a variety of pitfalls compared to the built-in Intellisense.
```

2024-03-07 20:05 UTC, rzblue commented on source/docs/software/advanced-gradlerio/gradlew-tasks.rst
> +    This file will be outputted under ``build/TargetedCompileCommands/targetplatformandbuildtype`` but needs to be moved to the root of your project. Make sure you have gitignored this file.
```suggestion
    This file will be saved in ``build/TargetedCompileCommands/targetplatformandbuildtype`` but needs to be moved to the root of your project. Make sure you have gitignored this file.
```
Also, most IDEs have an option to specify compile command file location

2024-03-16 21:20 UTC, sciencewhiz commented on source/docs/software/advanced-gradlerio/gradlew-tasks.rst
> +.. note::
I think this is better off as part of the description rather a note

2024-08-18 03:56 UTC, sciencewhiz approved these changes

2024-08-18 05:52 UTC, rzblue approved these changes

2024-08-18 14:08 UTC, merged