Controls Tutorial for Motion Profiling
wpilibsuite/frc-docs pull request #2589
Opened 2024-03-01 21:50 UTC by gerth2

Using vertical elevator as the driving example for now

Entering draft PR for comments. 

Will update as functionality is added

2024-03-08 03:49 UTC, gerth2 commented
Question for the group.

`TrapezoidProfile` from wpimath (or something similar) is needed to complete this PR.

Two options for how to generate it without blowing up scope:
1) rewrite by hand in .js
2) Use something like https://www.codeconvert.ai/app to auto-convert with some fixup.

AI code ownership can be fraught in a corporate context, but I'm not sure how much that applies in open source. Thoughts on the risk before we move forward with 2 over 1? I'm fine with either.

Note, as mentioned in the past, a nifty thing would be a webasm build of wpimath that we build these sims around. But that's still a longer lead-time item.

2024-03-13 03:42 UTC, sciencewhiz commented
> Two options for how to generate it without blowing up scope:
> 
>     1. rewrite by hand in .js
> 
>     2. Use something like https://www.codeconvert.ai/app to auto-convert with some fixup.

Or https://github.com/wpilibsuite/frc-docs/issues/1831

2024-10-08 16:30 UTC, gerth2 commented
In an attempt to not let this rot too much...

If 1831 doesn't have line of sight to get solved prior to 2025 season, would going back on the initial two options be acceptable?

2024-12-19 20:38 UTC, gerth2 commented
rewritten sans AI.

2024-12-26 03:42 UTC, calcmogul commented on source/_extensions/controls_js_sim/plant/vertical-elevator-plant.js
> +    const airResistanceAccel = -1.0 * Math.sign(velMPerS) * Math.pow(velMPerS, 2) * 0.2;
Is the air resistance contribution appropriately scaled?

2025-01-02 17:27 UTC, gerth2 commented on source/_extensions/controls_js_sim/plant/vertical-elevator-plant.js
> +    const airResistanceAccel = -1.0 * Math.sign(velMPerS) * Math.pow(velMPerS, 2) * 0.2;
it is not, that's actually force that I calculated. Will add a mass factor there. Will get rid of the magic constant too.

FWIW if we wanted to take it out I wouldn't be hung up on it. Its inclusion is only to add unmodeled disturbances so closed loop has something to do.

2025-01-03 03:00 UTC, calcmogul approved these changes

2025-01-03 04:10 UTC, jasondaming requested changes
I think we should also modify the "Introduction To Controls Tuning Tutorials" to reference the 4 (it says 3 at top) tutorials and link to this tutorial in the list of that last paragraph.

2025-01-03 04:10 UTC, jasondaming commented on source/docs/software/advanced-controls/introduction/tuning-elevator.rst
> +3. Increase :math:`K_g` as much as you can without the elevator moving upward. You will have to zero in on :math:`K_g` fairly precisely (at least four decimal places).
We should explain the discrepancy between the advice to go to 4 decimals and the ideal answer that is just 2.28

2025-01-03 04:23 UTC, gerth2 commented on source/docs/software/advanced-controls/introduction/tuning-elevator.rst
> +The tutorials below will demonstrate the behavior of the system under pure pure feedback (PID), and then combined feedforward-feedback with motion profiling control strategies.  Follow the instructio
only the purest of the pure feedback.

Lolz great catch

2025-01-03 04:26 UTC, gerth2 commented on source/docs/software/advanced-controls/introduction/tuning-elevator.rst
> +.. note:: To change the elevator setpoint, click on the desired height along the vertical support.
Lemme take a peek. I'd argue for consistent behavior across tutorials, but I don't recall offhand how the others worked.

2025-01-03 04:32 UTC, jasondaming commented on source/docs/software/advanced-controls/introduction/tuning-elevator.rst
> +.. note:: To change the elevator setpoint, click on the desired height along the vertical support.
The others work like this too so lets just keep it consistent

2025-01-03 16:24 UTC, gerth2 commented on source/docs/software/advanced-controls/introduction/tuning-elevator.rst
> +The operator will command a position that changes in "steps" - in one loop, the commanded position will snap from one value to a different one. Since it is not physically plausible for the elevator t
Got it, expanded a bit to make it more like a story - feel free to repoen if it's still confusing

2025-01-03 16:41 UTC, gerth2 commented on source/docs/software/advanced-controls/introduction/tuning-elevator.rst
> +.. note:: To change the elevator setpoint, click on the desired height along the vertical support.
Did a quick check, yea:

1) a _click_ will restart the sim
2) _click and drag_ allows the setpoint to be moved

FWIW... Implementing #2 here would be a decent scope expansion, both to the code logic and to the explanaion (how do profilers work with a continually-changing setpoint). As long as you're ok, I'd vote for this to be a next-round of tutorial expansion, and let this one focus on fixed setpoints?

2025-01-03 22:11 UTC, jasondaming commented
Did you choose not to add the link in the last intro paragraph?  That is fine if you don't want it in there but seems like it would go well

2025-01-03 22:28 UTC, jasondaming commented on source/docs/software/advanced-controls/introduction/tuning-elevator.rst
> +In this specific example: We assume there are is one or more *fixed positions* that our elevator needs to move to. The operator commands which position is desired.
```suggestion
In this specific example: We assume there are one or more *fixed positions* that our elevator needs to move to. The operator commands which position is desired.
```

2025-01-05 19:28 UTC, jasondaming approved these changes

2025-01-05 19:28 UTC, merged