Describe cosine compensation in swerve drive kinematics
wpilibsuite/frc-docs pull request #2661
Opened 2024-06-04 00:29 UTC by Alextopher

So called "cosine compensation" is a common swerve drive optimization that I believe could benefit from easier discoverability and explanation. 

I apologize I'm not familiar with wpilibc or robotpy, I would appreciate if someone could verify those code examples look right.

2024-06-04 00:32 UTC, calcmogul requested changes

2024-06-04 00:32 UTC, calcmogul commented on source/docs/software/kinematics-and-odometry/swerve-drive-kinematics.rst
> +      frontLeftOptimized.speedMetersPerSecond *= frontLeftOptimized.angle.minus(currentAngle).cos();
```suggestion
      frontLeftOptimized.speedMetersPerSecond *= frontLeftOptimized.angle.minus(currentAngle).getCos();
```

2024-06-04 00:34 UTC, calcmogul approved these changes

2024-06-04 02:56 UTC, sciencewhiz commented
Is there a reason that C++ uses a different variable name from Java and Python?

2024-06-04 09:44 UTC, Alextopher commented
> Is there a reason that C++ uses a different variable name from Java and Python?

I used the same variable names as the previous code example.

2024-06-12 14:07 UTC, sciencewhiz approved these changes

2024-06-12 14:08 UTC, merged