Remove usage of robotInit from FRC Docs
wpilibsuite/frc-docs pull request #2689
Opened 2024-08-04 03:30 UTC by DJB755

Remove usage of robotInit #2679

2024-08-04 03:33 UTC, DJB755 commented
Oop realized I did not go throught the examples linked in the docs, will do that before submitting the PR

2024-08-06 01:31 UTC, DJB755 commented
Remove usage of robotInit https://github.com/wpilibsuite/frc-docs/issues/2679 replaced with different constructor on the FRCDocs side, should I fork allwpilib too and change the examples there too before?

2024-08-06 03:36 UTC, sciencewhiz requested changes
In general, this needs more nuanced changes. I commented on a few places at the beginning, but these "rules" apply many more places.

- 
- Can't say Robot method or function, need to update those to say constructor
- When there's a description of a side effect that the user needs to be aware of, it's still appropriate to reference robotInit, as users can still use robotInit, we just don't want to encourage it's use with examples.
- There's cases where code samples say `void Robot()` these need to be updated since Robot isn't a method
- I suspect that the python changes aren't correct
- For the stacktraces article, I suspect the stack traces look significantly different when run from the constructor. This can't be updated just with find and replace. Per the previous point, I don't think this article is important to update as showing robotInit is ancillary to the point of explaining stack traces, but it would be bad to update the way it is that makes it wrong.

2024-08-06 03:36 UTC, sciencewhiz commented on source/docs/software/advanced-controls/trajectories/trajectory-generation.rst
> +.. note:: Generating a typical trajectory takes about 10 ms to 25 ms. This isn't long, but it's still highly recommended to generate all trajectories on startup (``Robot``).
This should say something like ``Robot`` constructor

2024-08-06 03:36 UTC, sciencewhiz commented on source/docs/software/basic-programming/alliancecolor.rst
> +Note that there are three cases: red, blue, and no color yet.  It is important that code handles the third case correctly because the alliance color will not be available until the Driver Station con
This shouldn't be changed, as now it's redundant

2024-08-06 03:36 UTC, sciencewhiz commented on source/docs/software/basic-programming/reading-stacktraces.rst
> +         Error at frc.robot.Robot.Robot(Robot.java:24): Unhandled exception: java.lang.NullPointerException
I suspect that this is not what the stack trace would look like

2024-08-06 12:06 UTC, spacey-sooty commented
Resolves https://github.com/wpilibsuite/frc-docs/issues/2679

2024-08-06 12:07 UTC, spacey-sooty commented
> Remove usage of robotInit #2679 replaced with different constructor on the FRCDocs side, should I fork allwpilib too and change the examples there too before?

allwpilib has already removed this https://github.com/wpilibsuite/allwpilib/pull/6623

2024-11-11 17:02 UTC, sciencewhiz commented
Superseded by #2841

2024-11-11 17:02 UTC, closed without merging