Convert headers to md
wpilibsuite/frc-docs pull request #2692
Opened 2024-08-11 21:23 UTC by TheTripleV

To be merged after #2690.

2024-08-14 03:35 UTC, sciencewhiz requested changes

2024-08-14 03:35 UTC, sciencewhiz commented on source/docs/contributing/frc-docs/style-guide.rst
> +## Headings
This section should be updated with the md syntax

2024-08-16 20:52 UTC, sciencewhiz commented
Because of the way it overrides doc8, I want to make sure it works on windows, linux and mac. What did you test it on?

2024-08-16 21:41 UTC, TheTripleV commented
I tested on Mac. And ci is Linux. So windows is the only one remaining.

2024-08-17 01:46 UTC, TheTripleV commented
Just tried this on windows, make.bat also works

2024-08-17 20:08 UTC, sciencewhiz approved these changes

2024-08-17 20:09 UTC, merged