Document TimesliceRobot template
wpilibsuite/frc-docs pull request #2752
Opened 2024-09-19 02:57 UTC by leongmichael

resolve #1446

2024-09-19 03:24 UTC, leongmichael commented
/format

2024-09-19 03:28 UTC, leongmichael commented
i realize there are various other examples not documented. would it be best to merge this first or do them all in this one PR?

2024-09-28 09:54 UTC, jasondaming commented
Looks like you have an annoying extra whitespace linting error probably just a space at the end of a line or on a blank line.

I would say it is up to you on the organization of this vs multiple PRs.  I think the only two template types that aren't documented are "skeletons" and "educational".  Skeletons could be generically mentioned in one paragraph towards the beginning.  Educational has a very narrow specific use case that I'm not sure it would be worth documenting here.

If you are looking for additional ideas for improving this document the 2 highest on my list would be:
1) Advice up front about making (or not making) a selection.  This is always difficult to do impartially but is often the most critical piece for helping teams.  In this case what I would stress is that starting from a template is IMO a really bad idea for a new user.  It leaves them with a lot of blank page fears and gives them little (other than the template comments) to guide them on the proper structure.  Instead new teams should be looking at an understanding the example most relevant to them and/or past team code with goals similar to theirs.  I think it would also be good to link to ["What is Command Based"](https://frcdocs.wpi.edu/en/latest/docs/software/commandbased/what-is-command-based.html) instead of referencing a tutuorial that no longer exists and linking to the index page.
2) Adding Python.  It has been a slow process for us to get Python added everywhere but we should do our best to link to it also in all situations where it has the same features and Java/C++ are explicitly linked.

2024-10-06 21:32 UTC, sciencewhiz requested changes

2024-10-06 21:54 UTC, sciencewhiz approved these changes

2024-10-06 21:54 UTC, merged