Add privacy policy
wpilibsuite/frc-docs pull request #2761
Opened 2024-09-27 06:25 UTC by PeterJohnson

2024-09-27 20:24 UTC, Gold856 requested changes

2024-09-27 20:24 UTC, Gold856 commented on source/docs/legal/privacy-policy.rst
> +The WPILib libraries do not collect personal information.  When run on the RoboRIO, the libraries collect limited metrics data (“usage reporting”) regarding what pieces of the libraries are used by t
```suggestion
The WPILib libraries do not collect personal information.  When run on the roboRIO, the libraries collect limited metrics data (“usage reporting”) regarding what pieces of the libraries are used by the deployed software (user-written code linked to the WPILib libraries).  Only when the robot code is running and connected to the competition field at a FIRST Robotics Competition event is this information shared with and stored by the Field Management System.  This information is associated solely with the FRC team and not with any individual.  An anonymized (team number removed) version of this metrics data is publicly shared by FIRST after each competition season, and is used to inform future development of library features.
```

2024-09-27 20:24 UTC, Gold856 commented on source/docs/legal/privacy-policy.rst
> +[Cloudflare Privacy Policy(https://www.cloudflare.com/privacypolicy/)
```suggestion
[Cloudflare Privacy Policy](https://www.cloudflare.com/privacypolicy/)
```

2024-09-28 09:02 UTC, jasondaming approved these changes

2024-09-28 09:02 UTC, merged