Replace trajectories page on Ramsete with LTV Unicycle
wpilibsuite/frc-docs pull request #2792
Opened 2024-10-14 13:53 UTC by spacey-sooty

RamseteController was deprecated in https://github.com/wpilibsuite/allwpilib/pull/6494 
Does 1 part of https://github.com/wpilibsuite/frc-docs/issues/2651

2024-10-16 11:42 UTC, Gold856 requested changes

2024-10-16 11:42 UTC, Gold856 commented on source/docs/software/advanced-controls/trajectories/ltv.rst
Should link to the LQR page that the API docs link to for tuning info and show the other constructors.

2025-01-03 05:47 UTC, calcmogul requested changes

2025-01-03 05:47 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +The LTV Unicycle controller should be initialized with four parameters. `qelms` is a vector of the maximum desired error tolerance in the X and Y directions and heading. `relms` is a vector of the de
`qelms` and `relms` are misspelled. LTVUnicycleController.java spells them `qelems` and `relems`, like "Q elements" and "R elements".

2025-01-03 05:47 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +The code example below initialize the LTV Unicycle Controller with `qelms` of 0.0625 m in X, 0.125 m in Y, and 2 radians in heading; `relms` of 1 m/s of linear velocity, and 2 rad/sec angular velocit
```suggestion
The code example below initializes the LTV Unicycle Controller with `qelms` of 0.0625 m in X, 0.125 m in Y, and 2 radians in heading; `relms` of 1 m/s of linear velocity, and 2 rad/sec angular velocity; `dt` of 20 ms; and `maxVelocity` of 9 m/s.
```
This should probably justify why the heading tolerance is so large so students don't repeatedly ask about it. It's to allow the y controller (crosstrack error controller) to overpower the heading controller so crosstrack error gets driven to zero.

2025-01-03 05:47 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +The LTV Unicycle controller returns "adjusted velocities" so that the when the robot tracks these velocities, it accurately reaches the goal point. The controller should be updated periodically with
This is very wordy, repeats itself, and repeats information from the next paragraph. Here's a shorter version.
```suggestion
The LTV Unicycle controller returns linear and angular velocity commands which, if followed, will make the robot accurately reach a goal state consisting of a desired pose, desired linear velocity, and desired angular velocity.
```

2025-01-03 05:47 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +.. note:: The "goal pose" represents the position that the robot should be at a particular timestep when tracking the trajectory. It does NOT represent the final endpoint of the trajectory.
This isn't entirely accurate. The trajectory classes define goal to be where the robot should be eventually, and they define reference to be where the robot should be right now.

2025-01-03 05:47 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +## Getting Adjusted Velocities
The proper technical term for them is velocity commands. They come from how the outer control loop (pose -> velocity) is commanding the inner control loop (velocity -> voltage/current).
```suggestion
## Getting Velocity Commands
```

2025-01-03 05:47 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +The controller can be updated using the ``Calculate`` (C++) / ``calculate`` (Java/Python) method. There are two overloads for this method. Both of these overloads accept the current robot position as
Note that the second overload only applies to those using the WPILib trajectory API, which is rare these days.
```suggestion
The controller can be updated using the ``Calculate`` (C++) / ``calculate`` (Java/Python) method. The first overload of this method accepts the current robot pose, desired robot pose, desired linear velocity, and desired angular velocity. The second overload accepts the current robot pose and desired pose, linear velocity, and angular velocity as a ``Trajectory.State`` object. This overload is ideal for those using the WPILib trajectory API.
```

2025-01-03 05:47 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +## Using the Adjusted Velocities
```suggestion
## Using the velocity commands
```

2025-01-03 05:47 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +The adjusted velocities are of type ``ChassisSpeeds``, which contains a ``vx`` (linear velocity in the forward direction), a ``vy`` (linear velocity in the sideways direction), and an ``omega`` (angu
```suggestion
The velocity commands are of type ``ChassisSpeeds``, which contains a ``vx`` (linear velocity in the forward direction), a ``vy`` (linear velocity in the sideways direction), and an ``omega`` (angular velocity around the center of the robot frame).
```

2025-01-03 05:47 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +The returned adjusted speeds can be converted to usable speeds using the kinematics classes for your drivetrain type. For example, the adjusted velocities can be converted to left and right velocitie
We should mention earlier in the article that this controller only applies to nonholonomic drivetrains like differential drive. Holonomic drivetrains can use more optimal controllers like separate decoupled PD controllers, because they don't have to deal with nonholonomic limitations like not being able to move sideways.

2025-01-03 05:47 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +Because these new left and right velocities are still speeds and not voltages, two PID Controllers, one for each side may be used to track these velocities. Either the WPILib PIDController ([C++](htt
```suggestion
These new left and right velocities are still speeds and not voltages, so two PID Controllers, one for each side, should be used to track them. You can use either the WPILib PIDController ([C++](https://github.wpilib.org/allwpilib/docs/release/cpp/classfrc_1_1_p_i_d_controller.html), [Java](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/controller/PIDController.html), :external:py:class:`Python <wpimath.controller.PIDController>`) or the Velocity PID feature on smart motor controllers such as the TalonSRX and the SPARK MAX.
```

2025-01-03 15:54 UTC, sciencewhiz commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +## Getting Adjusted Velocities
Should this also apply to the Ramsete article?

2025-01-03 16:28 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +## Getting Adjusted Velocities
Yes.

2025-01-06 12:38 UTC, Gold856 requested changes

2025-01-06 12:38 UTC, Gold856 commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +
Control is misspelled in `State Space contrl LQR tuning`

2025-01-22 05:39 UTC, calcmogul requested changes

2025-01-22 05:39 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +The LTV Unicycle controller should be initialized with four parameters. `qelems` is a vector of the maximum desired error tolerance in the X and Y directions and heading. `relems` is a vector of the
```suggestion
The LTV Unicycle controller should be initialized with four parameters. `qelems` is a vector of the maximum desired error tolerance in the X and Y directions and heading. `relems` is a vector of the desired control effort in linear velocity and angular velocity. `dt` represents the timestep used in calculations (the default loop rate of 20 ms is a reasonable value) and `maxVelocity` should be the max velocity your robot can achieve. See :ref:`The State Space control LQR Tuning <docs/software/advanced-controls/state-space/state-space-intro:LQR: tuning>` for more information on the effect of `qelems` and `relems` on the controller.
```

2025-01-22 05:39 UTC, calcmogul commented on source/docs/software/advanced-controls/trajectories/ltv.rst
> +   ChassisSpeeds adjustedSpeeds = controller.calculate(currentRobotPose, referencel);
```suggestion
   ChassisSpeeds adjustedSpeeds = controller.calculate(currentRobotPose, reference);
```

2025-01-22 16:48 UTC, calcmogul approved these changes

2025-01-22 17:45 UTC, sciencewhiz approved these changes

2025-01-23 19:46 UTC, merged