Change recommended swerve trajectory planner to Choreo
wpilibsuite/frc-docs pull request #2800
Opened 2024-10-15 06:30 UTC by spacey-sooty

2024-10-15 06:32 UTC, calcmogul commented
I'd link to both PathPlanner and Choreo, since Choreo can't do on-the-fly planning, and Choreo and PathPlanner have interop.

2024-10-15 06:32 UTC, TheTripleV commented
No library wars pls

Just include both?

2024-10-15 06:33 UTC, spacey-sooty commented
> No library wars pls

That wasn't the intention, Choreo is bundled in the installer whereas pathplanner isnt so imo it made more sense to recommend it. 

I can link to both

2024-10-16 00:40 UTC, spacey-sooty commented
> It still reads as pathplanner being an afterthought/lesser alternative

IMO since choreo is in the installer we should first recommend that then suggest pathplanner if people need features it offers

2024-10-16 03:02 UTC, calcmogul requested changes

2024-10-16 03:02 UTC, calcmogul commented on source/docs/software/pathplanning/pathweaver/index.rst
> +.. note:: Users may find [Choreo](https://sleipnirgroup.github.io/Choreo/) or [PathPlanner](https://github.com/mjansen4857/pathplanner) more usefu. They both have an inuitive user interface and swerv
```suggestion
.. note:: Users may find [Choreo](https://sleipnirgroup.github.io/Choreo/) or [PathPlanner](https://github.com/mjansen4857/pathplanner) more useful. They both have an intuitive user interface and swerve support. Users should already have access to Choreo as it is shipped with WPILib.
```

2024-10-16 03:02 UTC, calcmogul commented on source/docs/software/pathplanning/pathweaver/introduction.rst
> +.. note:: Users may find [Choreo](https://sleipnirgroup.github.io/Choreo/) or [PathPlanner](https://github.com/mjansen4857/pathplanner) more usefu. They both have an inuitive user interface and swerv
```suggestion
.. note:: Users may find [Choreo](https://sleipnirgroup.github.io/Choreo/) or [PathPlanner](https://github.com/mjansen4857/pathplanner) more useful. They both have an intuitive user interface and swerve support. Users should already have access to Choreo as it is shipped with WPILib.
```

2024-10-16 03:03 UTC, jasondaming commented on source/docs/software/pathplanning/pathweaver/introduction.rst
> +.. note:: Users may find [Choreo](https://sleipnirgroup.github.io/Choreo/) or [PathPlanner](https://github.com/mjansen4857/pathplanner) more usefu. They both have an inuitive user interface and swerv
```suggestion
.. note:: Users may find [Choreo](https://sleipnirgroup.github.io/Choreo/) or [PathPlanner](https://github.com/mjansen4857/pathplanner) more useful. They both have an inuitive user interface and swerve support. Users should already have access to Choreo as it is shipped with WPILib.
```

2024-10-16 04:38 UTC, jasondaming approved these changes

2024-10-16 04:38 UTC, merged