Add details about built-in shuffleboard plugins
wpilibsuite/frc-docs pull request #826
Opened 2020-09-14 13:05 UTC by carbotaniuman

2020-09-14 14:19 UTC, Daltz333 approved these changes

2020-09-14 14:42 UTC, sciencewhiz commented on source/docs/software/wpilib-tools/shuffleboard/custom-widgets/builtin-plugins.rst
> +Built-in Widgets
Shouldn't this be Built-in Plugins?

2020-09-15 05:35 UTC, Daltz333 requested changes

2020-09-15 05:35 UTC, Daltz333 commented on source/docs/software/wpilib-tools/shuffleboard/custom-widgets/custom-themes.rst
> +Loading themes via plugins
```suggestion
Loading Themes via Plugins
```

2020-09-15 05:35 UTC, Daltz333 commented on source/docs/software/wpilib-tools/shuffleboard/custom-widgets/custom-themes.rst
> +----------------------------------------------------
```suggestion
Modifying or Extending Shuffleboard’s Default Themes
----------------------------------------------------
```

2020-09-15 05:35 UTC, Daltz333 commented on source/docs/software/wpilib-tools/shuffleboard/custom-widgets/custom-themes.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
Source Code for the CSS Files
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Case overline

2020-09-15 05:35 UTC, Daltz333 commented on source/docs/software/wpilib-tools/shuffleboard/custom-widgets/custom-themes.rst
> +""""""""""""""""""""""""""""""
```suggestion
Material Design Color Swatches
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Use =, -, ^, ~ per style guide

2020-09-15 05:35 UTC, Daltz333 commented on source/docs/software/wpilib-tools/shuffleboard/custom-widgets/custom-themes.rst
> +""""""""""""""""""""""""""""
```suggestion
Overriding the Swatch Colors
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2020-09-15 05:35 UTC, Daltz333 commented on source/docs/software/wpilib-tools/shuffleboard/custom-widgets/custom-themes.rst
> +Replacing the blue shades in the light theme with red
Can we rename this to something shorter?

2020-09-15 05:35 UTC, Daltz333 commented on source/docs/software/wpilib-tools/shuffleboard/custom-widgets/custom-themes.rst
> +Replacing the red shades in the dark theme with blue
Little bit of a long title here. Can this get renamed to something shorter?

2020-09-17 16:10 UTC, AustinShalit commented on source/docs/software/wpilib-tools/shuffleboard/custom-widgets/custom-themes.rst
> +Replacnig red with blue (dark)
```suggestion
Replacing red with blue (dark)
```

2020-09-20 03:56 UTC, Daltz333 approved these changes

2020-09-20 03:57 UTC, merged