Cleanup Radio Programming Article
wpilibsuite/frc-docs pull request #875
Opened 2020-10-08 04:29 UTC by Daltz333

- Fix punctuation
- Use guilabels
- Update images to Windows 10 for applicable parts
- Fix formatting

2020-10-08 04:31 UTC, prateekma commented on source/docs/zero-to-robot/step-2/radio-programming.rst
> +.. important:: Please note that the radio configuration utility requires Java 8, not Java 11 that is included with the WPILib installation. This can be installed alongside the WPILib Java by download
Check spelling of "privileges".

2020-10-08 19:33 UTC, AustinShalit requested changes

2020-10-08 19:33 UTC, AustinShalit commented on source/docs/zero-to-robot/step-2/radio-programming.rst
> +.. note:: If you need to locate the program, it is installed to ``C:\Program Files\FRC Radio Configuration Utility``. For 32-bit machines the path is ``C:\Program Files (x86)\FRC Radio Configuration
It is located in `(x86)` regardless of how many bits the machines has.

2020-10-08 19:33 UTC, AustinShalit commented on source/docs/zero-to-robot/step-2/radio-programming.rst
> +Open-Mesh Firmware Note
`Open Mesh` is correct

2020-10-08 19:33 UTC, AustinShalit commented on source/docs/zero-to-robot/step-2/radio-programming.rst
> +Loading FRC Firmware to Open-Mesh Radio
```suggestion
Loading FRC Firmware to Open Mesh Radio
```

2020-10-08 19:33 UTC, AustinShalit commented on source/docs/zero-to-robot/step-2/radio-programming.rst
> +2. Make sure the Open-Mesh radio is selected in the Radio dropdown.
```suggestion
2. Make sure the Open Mesh radio is selected in the Radio dropdown.
```

2020-10-08 19:33 UTC, AustinShalit commented on source/docs/zero-to-robot/step-2/radio-programming.rst
> +.. note:: Firewall and BW Limit only apply to the Open-Mesh radios. These options have no effect on D-Link radios.
```suggestion
.. note:: Firewall and BW Limit only apply to the Open Mesh radios. These options have no effect on D-Link radios.
```

2020-10-08 19:33 UTC, AustinShalit commented on source/docs/zero-to-robot/step-2/radio-programming.rst
> +.. warning:: The "Firewall" option configures the radio to emulate the field firewall. This means that you will not be able to deploy code wirelessly with this option enabled. This is useful for simu
```suggestion
.. warning:: The "Firewall" option configures the radio to emulate the field firewall. This means that you will not be able to deploy code wirelessly with this option enabled. This is useful for simulating blocked ports that exist at competitions.
```

2020-10-08 19:33 UTC, AustinShalit commented on source/docs/zero-to-robot/step-2/radio-programming.rst
> +If the your computer is running Windows Vista or Windows 7, a prompt may appear about allowing the configuration utility to make changes to the computer. Click :guilabel:`Yes` if the prompt appears.
```suggestion
If the your computer is running Windows 7, a prompt may appear about allowing the configuration utility to make changes to the computer. Click :guilabel:`Yes` if the prompt appears.
```

2020-10-09 02:34 UTC, AustinShalit approved these changes

2020-10-09 02:57 UTC, merged