Update Java q and r example to use N2 instead of 2
wpilibsuite/frc-docs pull request #887
Opened 2020-10-08 21:40 UTC by mcm001

2020-10-08 21:44 UTC, calcmogul commented
To be clear, that code is being updated so it actually compiles.

2020-10-10 13:55 UTC, prateekma requested changes

2020-10-10 13:55 UTC, prateekma commented on source/docs/software/advanced-controls/state-space/state-space-intro.rst
> +          LinearQuadraticRegulator<2, 1> controller{
Why are the elements different between Java and C++?

2020-10-10 16:01 UTC, calcmogul commented on source/docs/software/advanced-controls/state-space/state-space-intro.rst
> +         LinearQuadtraticRegulator<N2, N1, N1> controller = new LinearQuadraticRegulator(system,
This still doesn't compile.

2020-10-16 01:07 UTC, calcmogul commented on source/docs/software/advanced-controls/state-space/state-space-intro.rst
> +         // Example system -- must be changed to match your robot.
The comment indentation is off by one space.

2020-10-16 01:10 UTC, calcmogul approved these changes

2020-10-16 01:13 UTC, Daltz333 approved these changes

2020-10-16 01:13 UTC, merged