Add docs on scheduling functions in new convenience features section
wpilibsuite/frc-docs pull request #914
Opened 2020-11-01 00:52 UTC by prateekma

Closes #912

2020-11-01 01:04 UTC, calcmogul requested changes

2020-11-01 01:04 UTC, calcmogul commented on source/docs/software/convenience-features/scheduling-functions.rst
> +The ``addPeriodic()`` (Java) / ``AddPeriodic()`` (C++) method takes in a lambda (the function to run), along with the requested frequency and an optional offset from the common starting time. The opt
```suggestion
The ``addPeriodic()`` (Java) / ``AddPeriodic()`` (C++) method takes in a lambda (the function to run), along with the requested period and an optional offset from the common starting time. The optional third argument is useful for scheduling a function in a different timeslot relative to the other ``TimedRobot`` periodic methods.
```

2020-11-01 02:02 UTC, Daltz333 commented
Should we link to Javadocs?

2020-11-01 02:15 UTC, prateekma commented
The Javadocs / Doxygen don't explain anything more than we do here; we've covered everything in them.

2020-11-01 09:49 UTC, calcmogul requested changes

2020-11-01 09:49 UTC, calcmogul commented on source/docs/software/convenience-features/scheduling-functions.rst
> +In order to be able to run certain functions at a rate that is faster than the default ``TimedRobot`` periodic update rate (20 ms), an ``addPeriodic()`` method has been added to ``TimedRobot``. Previ
```suggestion
``TimedRobot``'s ``addPeriodic()`` method allows one to run custom methods at a rate faster than the default ``TimedRobot`` periodic update rate (20 ms). Previously, teams had to make a ``Notifier`` to run feedback controllers more often than the ``TimedRobot`` loop period of 20 ms (running ``TimedRobot`` more often than this is not advised). Now, users can run feedback controllers more often than the main robot loop, but synchronously with the ``TimedRobot`` periodic functions, eliminating potential thread safety issues.
```

2020-11-01 09:50 UTC, calcmogul commented on source/docs/software/convenience-features/scheduling-functions.rst
> +In order to be able to run certain functions at a rate that is faster than the default ``TimedRobot`` periodic update rate (20 ms), an ``addPeriodic()`` method has been added to ``TimedRobot``. Previ
Just some more wordsmithing.

2020-11-01 09:52 UTC, calcmogul commented on source/docs/software/convenience-features/scheduling-functions.rst
> +                }
We should add closing braces to the class declarations in the examples.

2020-11-01 20:46 UTC, calcmogul approved these changes

2020-11-02 04:55 UTC, Daltz333 approved these changes

2020-11-02 04:56 UTC, merged