Add odometry reset docs and new PathWeaver coordinate info
wpilibsuite/frc-docs pull request #937
Opened 2020-11-16 15:58 UTC by prateekma

2020-11-17 02:59 UTC, sciencewhiz commented on source/docs/software/examples-tutorials/trajectory-tutorial/creating-following-trajectory.rst
>  .. todo:: link to ``relativeTo`` api docs once they're uploaded
This todo can be fixed now, right?

2020-11-17 02:59 UTC, sciencewhiz commented on source/docs/software/wpilib-tools/pathweaver/integrating-robot-program.rst
> +.. important:: To be compatible with the ``Field2d`` view in the simulator GUI, the coordinates for the exported JSON have changed. Previously (before 2021), the range of the y-coordinate was from -2
I think it would be helpful to say which coordinate is the top of the screen and which is bottom.

2020-11-20 01:54 UTC, calcmogul approved these changes

2020-11-20 02:05 UTC, Daltz333 requested changes

2020-11-20 02:05 UTC, Daltz333 commented on source/docs/software/examples-tutorials/trajectory-tutorial/creating-following-trajectory.rst
> +.. note:: It is very important that the initial robot pose match the first pose in the trajectory.  For the purposes of our example, the robot will be reliably starting at a position of ``(0,0)`` wit
I think this is a bit verbose for a ``.. note::`` I would just make this a regular paragraph

2020-11-20 02:18 UTC, Daltz333 approved these changes

2020-11-20 02:18 UTC, merged