Add code example for LQR input delay compensation
wpilibsuite/frc-docs pull request #945
Opened 2020-11-20 21:28 UTC by prateekma

Closes #893 
Waiting on merge of https://github.com/wpilibsuite/allwpilib/pull/2878

2020-11-21 01:08 UTC, calcmogul requested changes

2020-11-21 01:08 UTC, calcmogul commented on source/docs/software/advanced-controls/state-space/state-space-debugging.rst
> +Often times, some sensor input data (i.e. velocity readings) may be delayed due to onboard filtering that smart motor controllers tend to perform. By default, LQR's K gain assumes minimal input delay
```suggestion
Often times, some sensor input data (i.e. velocity readings) may be delayed due to onboard filtering that smart motor controllers tend to perform. By default, LQR's K gain assumes no input delay, so introducing significant delay on the order of tens of milliseconds can cause instability. To combat this, the LQR's K gain can be reduced, trading off performance for stability. A code example for how to compensate for this latency in a mathematically rigorous is available :ref:`here <docs/software/advanced-controls/state-space/state-space-intro:LQR and Measurement Latency Compensation>`.
```

2020-11-21 05:55 UTC, calcmogul approved these changes

2020-11-22 01:22 UTC, Daltz333 approved these changes

2020-11-22 01:23 UTC, merged