Curvature drive clarification
wpilibsuite/frc-docs pull request #950
Opened 2020-11-22 17:52 UTC by mcm001

2020-11-22 17:54 UTC, AustinShalit commented on source/docs/software/actuators/wpi-drive-classes.rst
> +an additional parametr.
```suggestion
an additional parameter. 
```

2020-11-23 01:15 UTC, Daltz333 requested changes

2020-11-23 01:15 UTC, Daltz333 commented on source/docs/software/actuators/wpi-drive-classes.rst
> +Like Arcade Drive, the Curvature Drive mode is used to control the drivetrain using speed/throttle and rotation rate. The difference is that the rotation control input controls the radius of curvatur
What is this additional parameter?

2020-11-23 20:50 UTC, mcm001 commented on source/docs/software/actuators/wpi-drive-classes.rst
> +Like Arcade Drive, the Curvature Drive mode is used to control the drivetrain using speed/throttle and rotation rate. The difference is that the rotation control input controls the radius of curvatur
this better?

2020-11-24 04:13 UTC, Daltz333 commented on source/docs/software/actuators/wpi-drive-classes.rst
> +Like Arcade Drive, the Curvature Drive mode is used to control the drivetrain using speed/throttle and rotation rate. The difference is that the rotation control input controls the radius of curvatur
I was more wanting a code example.

2020-11-25 04:34 UTC, mcm001 commented on source/docs/software/actuators/wpi-drive-classes.rst
> +Like Arcade Drive, the Curvature Drive mode is used to control the drivetrain using speed/throttle and rotation rate. The difference is that the rotation control input controls the radius of curvatur
There is one?

2020-11-25 15:30 UTC, Daltz333 commented on source/docs/software/actuators/wpi-drive-classes.rst
> +Like Arcade Drive, the Curvature Drive mode is used to control the drivetrain using speed/throttle and rotation rate. The difference is that the rotation control input controls the radius of curvatur
Oh lol

2020-11-26 02:17 UTC, Daltz333 approved these changes

2020-11-26 15:09 UTC, merged