Link to local api docs in installer included docs
wpilibsuite/frc-docs pull request #959
Opened 2020-11-29 02:58 UTC by TheTripleV

closes #728 .

If docs are accessed from the wpilib install location, the links to the Java/C++ Api Docs will go to local versions instead of online versions.

Tested on Mac.

2020-11-29 03:00 UTC, Daltz333 commented on source/cpp-api-docs-redirect.rst
> +======================
```suggestion
=====================
```

2020-11-29 03:35 UTC, TheTripleV commented
rebased off master

2020-11-29 03:47 UTC, Daltz333 commented
Not sure if it's possible to add a check to confirm that the destination exists (locally), for cases where the RTD docs is manually downloaded

2020-11-29 03:51 UTC, Daltz333 commented
I have confirmed that this works on Windows

2020-11-29 04:17 UTC, prateekma requested changes
Change Api -> API

2020-11-29 05:09 UTC, prateekma requested changes

2020-11-29 05:09 UTC, prateekma commented on source/cpp-api-docs-redirect.rst
> +Oops. Your browser doesn't support Javascript.
Javascript -> JavaScript

2020-11-29 19:00 UTC, Daltz333 submitted a review, later dismissed

2020-12-02 08:06 UTC, TheTripleV commented
The links to the api docs in `docs/software/advanced-controls/trajectories/ramsete.rst` also need to be fixed.
They link to specific pages in the api docs while this PR currently only supports linking to the root of the api docs.

Solution: 
In ramsete.rst, we can link to the built redirect html file instead of the rst. The desired path (relative to the root of the api docs) can be passed in the query portion of the url and the js can redirect correctly.

2020-12-02 14:40 UTC, sciencewhiz commented
I believe there are many more links to the api docs, especially in the command section.

2020-12-02 15:38 UTC, TheTripleV commented
I think all links can be automatically taken care of using sphinx's build-finished event.

1. The redirecting file will be updated to allow for redirecting to any page within the api docs.
2. On build-finished, all links to the api docs in frc-docs will be replaced with redirecting ones.

The only downside I see to this solution as opposed to redirecting in the wpilib installer is that this solution requires that javascript is enabled.

So I guess the decision is where to do the find and replace, here or in the wpilib installer?

2020-12-02 17:53 UTC, Daltz333 commented
It can be done via JavaScript. I don't think we need to support a no-javascript environment, as the website is already severely broken without it.

2020-12-11 02:41 UTC, Daltz333 commented on source/java-api-docs-redirect.rst
> +WPILIB Java API Documentation
WPILib

2020-12-11 03:56 UTC, TheTripleV commented
Changes:
- All links to the api docs from frc-docs are properly redirected, including links to specific api pages
- The hash is propagated to the redirected url
- Code duplication reduced - the main redirecting js code only exists once now.

Functionality:
All links to the api docs are replaced with a link to a dummy file that conditionally redirects to local/online versions of the api docs. Links to the api docs of form `https://first.wpi.edu/FRC/roborio/release/docs/LANG/PAGE#HASH` are replaced with `api-docs-redirect.html?path=LANG/PAGE&hash=HASH` which is then parsed by the js in `api-docs-redirect.rst`

Note: When `index.rst` is read, `api-docs-redirect.html` has not been built yet, resulting in an error. This is why `cpp-api-docs-redirect.rst` and `java-api-docs-redirect.rst` exist. Users clicking on the api docs links in the nav sidebar will face a double redirect while all other api docs links only result in a single redirect.

2020-12-11 04:56 UTC, TheTripleV commented
Because of the double redirect on the sidebar, the browser back doesn't work. Need to implement another workaround. Will do after AoC.

2020-12-11 21:40 UTC, TheTripleV commented
Changes:
The dummy redirecting page has been removed. Now, on page load, all api docs links are changed in the DOM. This makes the redirects "instant" and doesn't mangle the browser history.

2020-12-17 09:14 UTC, AustinShalit commented on source/_static/js/api-docs-redirect.js
> +}, false);
```suggestion
}, false);

```

2020-12-17 17:26 UTC, Daltz333 approved these changes

2020-12-17 17:26 UTC, merged