changed from drive to flywheel
wpilibsuite/frc-docs pull request #964
Opened 2020-11-30 22:48 UTC by jasondaming

Closes #958

2020-11-30 23:02 UTC, prateekma requested changes
Although motor safety is not enabled by default on individual motors, we should a note mentioning that this will not work if teams have explicitly enabled it.

2020-12-01 03:00 UTC, jasondaming commented
I feel like if you know enough to enable motor safety then you know much more than this example is aimed at.  This is not true of motor safety for drive as that is enabled by default and this could be used with true understanding of why motor safety would prevent it from running.

What causes this command to stop?  I think this is true of a couple of examples in the code but I don't think that this code makes sense completely.  We just have to weigh is it worth adding a decorator to increase the usefulness of the code while making it slightly more complex?  I am seriously tempted to add a .timeout so it actually has a reason to stop, thoughts?

2020-12-02 18:17 UTC, prateekma approved these changes

2020-12-03 15:49 UTC, AustinShalit approved these changes

2020-12-03 15:49 UTC, merged