FRC branding
wpilibsuite/frc-docs pull request #983
Opened 2020-12-06 20:18 UTC by jasondaming

Closes #250 

That was a lot of corrections!

2020-12-06 20:59 UTC, sciencewhiz requested changes

2020-12-06 20:59 UTC, sciencewhiz commented on source/docs/contributing/frc-docs/build-instructions.rst
> +This document contains information on how to build the HTML, PDF, and EPUB versions of the frc\ |reg|-docs site. frc-docs uses Sphinx as the documentation generator. This document also assumes you ha
frc-docs is a name. It shouldn't have the registered trademark symbol inserted

2020-12-06 20:59 UTC, sciencewhiz commented on source/docs/software/vscode-overview/wpilib-commands-vscode.rst
> +- **WPILib: Set VS Code Java Home to FRC\ |reg| Home** - Set the VS Code Java Home variable to point to the Java Home discovered by the FRC extension. This is needed if not using the offline installe
This is a title and shouldnt have the registered trademark symbol

2020-12-07 02:30 UTC, sciencewhiz submitted a review, later dismissed

2020-12-07 02:40 UTC, Daltz333 commented
Titles should not have the registered trademark. This breaks translation.

2020-12-07 03:31 UTC, jasondaming commented
branding from titles is removed

2020-12-07 04:00 UTC, Daltz333 approved these changes

2020-12-07 04:00 UTC, merged